// <auto-generated>
// This file was generated automatically by Tools/CodeGen/GenerateOneOf.py.
// </auto-generated>
using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace Unicore.Monads
{
    /// <summary>
    /// Represents discriminated union that contains one value of types <typeparamref name="T0" /> through <typeparamref name="T7" />.
    /// </summary>
    /// <typeparam name="T0">Type of branch 0.</typeparam>
    /// <typeparam name="T1">Type of branch 1.</typeparam>
    /// <typeparam name="T2">Type of branch 2.</typeparam>
    /// <typeparam name="T3">Type of branch 3.</typeparam>
    /// <typeparam name="T4">Type of branch 4.</typeparam>
    /// <typeparam name="T5">Type of branch 5.</typeparam>
    /// <typeparam name="T6">Type of branch 6.</typeparam>
    /// <typeparam name="T7">Type of branch 7.</typeparam>
    public readonly struct OneOf<T0, T1, T2, T3, T4, T5, T6, T7> : IEquatable<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>>
    {
        private readonly object _value;
        private readonly byte _index;
        private readonly bool _hasValue;

        /// <summary>
        /// Gets branch T0 value.
        /// </summary>
        /// <value>A value stored in branch T0.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T0.</exception>
        public T0 AsT0 => _hasValue
            ? _index == 0
                ? (T0)_value
                : throw CreateWrongBranchException("T0")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T0.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T0; otherwise, <see langword="false" />.</value>
        public bool IsT0 => _index == 0;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T0 value.
        /// </summary>
        /// <param name="value">A value to store in branch T0.</param>
        public OneOf(T0 value)
        {
            _value = value;
            _index = 0;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T1 value.
        /// </summary>
        /// <value>A value stored in branch T1.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T1.</exception>
        public T1 AsT1 => _hasValue
            ? _index == 1
                ? (T1)_value
                : throw CreateWrongBranchException("T1")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T1.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T1; otherwise, <see langword="false" />.</value>
        public bool IsT1 => _index == 1;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T1 value.
        /// </summary>
        /// <param name="value">A value to store in branch T1.</param>
        public OneOf(T1 value)
        {
            _value = value;
            _index = 1;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T2 value.
        /// </summary>
        /// <value>A value stored in branch T2.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T2.</exception>
        public T2 AsT2 => _hasValue
            ? _index == 2
                ? (T2)_value
                : throw CreateWrongBranchException("T2")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T2.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T2; otherwise, <see langword="false" />.</value>
        public bool IsT2 => _index == 2;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T2 value.
        /// </summary>
        /// <param name="value">A value to store in branch T2.</param>
        public OneOf(T2 value)
        {
            _value = value;
            _index = 2;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T3 value.
        /// </summary>
        /// <value>A value stored in branch T3.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T3.</exception>
        public T3 AsT3 => _hasValue
            ? _index == 3
                ? (T3)_value
                : throw CreateWrongBranchException("T3")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T3.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T3; otherwise, <see langword="false" />.</value>
        public bool IsT3 => _index == 3;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T3 value.
        /// </summary>
        /// <param name="value">A value to store in branch T3.</param>
        public OneOf(T3 value)
        {
            _value = value;
            _index = 3;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T4 value.
        /// </summary>
        /// <value>A value stored in branch T4.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T4.</exception>
        public T4 AsT4 => _hasValue
            ? _index == 4
                ? (T4)_value
                : throw CreateWrongBranchException("T4")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T4.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T4; otherwise, <see langword="false" />.</value>
        public bool IsT4 => _index == 4;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T4 value.
        /// </summary>
        /// <param name="value">A value to store in branch T4.</param>
        public OneOf(T4 value)
        {
            _value = value;
            _index = 4;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T5 value.
        /// </summary>
        /// <value>A value stored in branch T5.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T5.</exception>
        public T5 AsT5 => _hasValue
            ? _index == 5
                ? (T5)_value
                : throw CreateWrongBranchException("T5")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T5.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T5; otherwise, <see langword="false" />.</value>
        public bool IsT5 => _index == 5;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T5 value.
        /// </summary>
        /// <param name="value">A value to store in branch T5.</param>
        public OneOf(T5 value)
        {
            _value = value;
            _index = 5;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T6 value.
        /// </summary>
        /// <value>A value stored in branch T6.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T6.</exception>
        public T6 AsT6 => _hasValue
            ? _index == 6
                ? (T6)_value
                : throw CreateWrongBranchException("T6")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T6.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T6; otherwise, <see langword="false" />.</value>
        public bool IsT6 => _index == 6;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T6 value.
        /// </summary>
        /// <param name="value">A value to store in branch T6.</param>
        public OneOf(T6 value)
        {
            _value = value;
            _index = 6;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T7 value.
        /// </summary>
        /// <value>A value stored in branch T7.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T7.</exception>
        public T7 AsT7 => _hasValue
            ? _index == 7
                ? (T7)_value
                : throw CreateWrongBranchException("T7")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T7.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T7; otherwise, <see langword="false" />.</value>
        public bool IsT7 => _index == 7;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2, T3, T4, T5, T6, T7}" /> struct with branch T7 value.
        /// </summary>
        /// <param name="value">A value to store in branch T7.</param>
        public OneOf(T7 value)
        {
            _value = value;
            _index = 7;
            _hasValue = true;
        }

        /// <summary>
        /// Projects current union into another value by selecting mapper for active branch.
        /// </summary>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <param name="map3">A mapping function for branch T3 value.</param>
        /// <param name="map4">A mapping function for branch T4 value.</param>
        /// <param name="map5">A mapping function for branch T5 value.</param>
        /// <param name="map6">A mapping function for branch T6 value.</param>
        /// <param name="map7">A mapping function for branch T7 value.</param>
        /// <returns>A mapped value produced by selected mapper.</returns>
        public TReturn Map<TReturn>(
            Func<T0, TReturn> map0,
            Func<T1, TReturn> map1,
            Func<T2, TReturn> map2,
            Func<T3, TReturn> map3,
            Func<T4, TReturn> map4,
            Func<T5, TReturn> map5,
            Func<T6, TReturn> map6,
            Func<T7, TReturn> map7
        )
        {
            return _index switch
            {
                0 => map0(AsT0),
                1 => map1(AsT1),
                2 => map2(AsT2),
                3 => map3(AsT3),
                4 => map4(AsT4),
                5 => map5(AsT5),
                6 => map6(AsT6),
                7 => map7(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value by selecting mapper for active branch and passing shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="context">A context value passed to selected mapper.</param>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <param name="map3">A mapping function for branch T3 value.</param>
        /// <param name="map4">A mapping function for branch T4 value.</param>
        /// <param name="map5">A mapping function for branch T5 value.</param>
        /// <param name="map6">A mapping function for branch T6 value.</param>
        /// <param name="map7">A mapping function for branch T7 value.</param>
        /// <returns>A mapped value produced by selected mapper.</returns>
        public TReturn Map<TContext, TReturn>(
            TContext context,
            Func<TContext, T0, TReturn> map0,
            Func<TContext, T1, TReturn> map1,
            Func<TContext, T2, TReturn> map2,
            Func<TContext, T3, TReturn> map3,
            Func<TContext, T4, TReturn> map4,
            Func<TContext, T5, TReturn> map5,
            Func<TContext, T6, TReturn> map6,
            Func<TContext, T7, TReturn> map7
        )
        {
            return _index switch
            {
                0 => map0(context, AsT0),
                1 => map1(context, AsT1),
                2 => map2(context, AsT2),
                3 => map3(context, AsT3),
                4 => map4(context, AsT4),
                5 => map5(context, AsT5),
                6 => map6(context, AsT6),
                7 => map7(context, AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value asynchronously by selecting mapper for active branch.
        /// </summary>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <param name="map3">A mapping function for branch T3 value.</param>
        /// <param name="map4">A mapping function for branch T4 value.</param>
        /// <param name="map5">A mapping function for branch T5 value.</param>
        /// <param name="map6">A mapping function for branch T6 value.</param>
        /// <param name="map7">A mapping function for branch T7 value.</param>
        /// <returns>A task that produces mapped value from selected mapper.</returns>
        public UniTask<TReturn> MapAsync<TReturn>(
            Func<T0, UniTask<TReturn>> map0,
            Func<T1, UniTask<TReturn>> map1,
            Func<T2, UniTask<TReturn>> map2,
            Func<T3, UniTask<TReturn>> map3,
            Func<T4, UniTask<TReturn>> map4,
            Func<T5, UniTask<TReturn>> map5,
            Func<T6, UniTask<TReturn>> map6,
            Func<T7, UniTask<TReturn>> map7
        )
        {
            return _index switch
            {
                0 => map0(AsT0),
                1 => map1(AsT1),
                2 => map2(AsT2),
                3 => map3(AsT3),
                4 => map4(AsT4),
                5 => map5(AsT5),
                6 => map6(AsT6),
                7 => map7(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value asynchronously by selecting mapper for active branch and passing shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="context">A context value passed to selected mapper.</param>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <param name="map3">A mapping function for branch T3 value.</param>
        /// <param name="map4">A mapping function for branch T4 value.</param>
        /// <param name="map5">A mapping function for branch T5 value.</param>
        /// <param name="map6">A mapping function for branch T6 value.</param>
        /// <param name="map7">A mapping function for branch T7 value.</param>
        /// <returns>A task that produces mapped value from selected mapper.</returns>
        public UniTask<TReturn> MapAsync<TContext, TReturn>(
            TContext context,
            Func<TContext, T0, UniTask<TReturn>> map0,
            Func<TContext, T1, UniTask<TReturn>> map1,
            Func<TContext, T2, UniTask<TReturn>> map2,
            Func<TContext, T3, UniTask<TReturn>> map3,
            Func<TContext, T4, UniTask<TReturn>> map4,
            Func<TContext, T5, UniTask<TReturn>> map5,
            Func<TContext, T6, UniTask<TReturn>> map6,
            Func<TContext, T7, UniTask<TReturn>> map7
        )
        {
            return _index switch
            {
                0 => map0(context, AsT0),
                1 => map1(context, AsT1),
                2 => map2(context, AsT2),
                3 => map3(context, AsT3),
                4 => map4(context, AsT4),
                5 => map5(context, AsT5),
                6 => map6(context, AsT6),
                7 => map7(context, AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Gets branch T0 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T0 value if it exists; otherwise, the default value of <typeparamref name="T0" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T0; otherwise, <see langword="false" />.</returns>
        public bool TryGetT0(out T0 value)
        {
            if (IsT0)
            {
                value = AsT0;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T0 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T0 value or <paramref name="defaultValue" />.</returns>
        public T0 GetT0OrDefault(T0 defaultValue = default) => IsT0 ? AsT0 : defaultValue;

        /// <summary>
        /// Gets branch T1 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T1 value if it exists; otherwise, the default value of <typeparamref name="T1" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T1; otherwise, <see langword="false" />.</returns>
        public bool TryGetT1(out T1 value)
        {
            if (IsT1)
            {
                value = AsT1;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T1 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T1 value or <paramref name="defaultValue" />.</returns>
        public T1 GetT1OrDefault(T1 defaultValue = default) => IsT1 ? AsT1 : defaultValue;

        /// <summary>
        /// Gets branch T2 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T2 value if it exists; otherwise, the default value of <typeparamref name="T2" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T2; otherwise, <see langword="false" />.</returns>
        public bool TryGetT2(out T2 value)
        {
            if (IsT2)
            {
                value = AsT2;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T2 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T2 value or <paramref name="defaultValue" />.</returns>
        public T2 GetT2OrDefault(T2 defaultValue = default) => IsT2 ? AsT2 : defaultValue;

        /// <summary>
        /// Gets branch T3 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T3 value if it exists; otherwise, the default value of <typeparamref name="T3" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T3; otherwise, <see langword="false" />.</returns>
        public bool TryGetT3(out T3 value)
        {
            if (IsT3)
            {
                value = AsT3;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T3 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T3 value or <paramref name="defaultValue" />.</returns>
        public T3 GetT3OrDefault(T3 defaultValue = default) => IsT3 ? AsT3 : defaultValue;

        /// <summary>
        /// Gets branch T4 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T4 value if it exists; otherwise, the default value of <typeparamref name="T4" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T4; otherwise, <see langword="false" />.</returns>
        public bool TryGetT4(out T4 value)
        {
            if (IsT4)
            {
                value = AsT4;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T4 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T4 value or <paramref name="defaultValue" />.</returns>
        public T4 GetT4OrDefault(T4 defaultValue = default) => IsT4 ? AsT4 : defaultValue;

        /// <summary>
        /// Gets branch T5 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T5 value if it exists; otherwise, the default value of <typeparamref name="T5" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T5; otherwise, <see langword="false" />.</returns>
        public bool TryGetT5(out T5 value)
        {
            if (IsT5)
            {
                value = AsT5;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T5 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T5 value or <paramref name="defaultValue" />.</returns>
        public T5 GetT5OrDefault(T5 defaultValue = default) => IsT5 ? AsT5 : defaultValue;

        /// <summary>
        /// Gets branch T6 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T6 value if it exists; otherwise, the default value of <typeparamref name="T6" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T6; otherwise, <see langword="false" />.</returns>
        public bool TryGetT6(out T6 value)
        {
            if (IsT6)
            {
                value = AsT6;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T6 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T6 value or <paramref name="defaultValue" />.</returns>
        public T6 GetT6OrDefault(T6 defaultValue = default) => IsT6 ? AsT6 : defaultValue;

        /// <summary>
        /// Gets branch T7 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T7 value if it exists; otherwise, the default value of <typeparamref name="T7" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T7; otherwise, <see langword="false" />.</returns>
        public bool TryGetT7(out T7 value)
        {
            if (IsT7)
            {
                value = AsT7;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T7 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T7 value or <paramref name="defaultValue" />.</returns>
        public T7 GetT7OrDefault(T7 defaultValue = default) => IsT7 ? AsT7 : defaultValue;

        /// <summary>
        /// Projects branch T0 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut0">Type of mapped branch T0.</typeparam>
        /// <param name="map">A mapping function for branch T0 value.</param>
        /// <returns>A union with mapped branch T0 or original value from another branch.</returns>
        public OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7> MapT0<TOut0>(Func<T0, TOut0> map)
        {
            return IsT0 ? new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(map(AsT0)) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T0 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut0">Type of mapped branch T0.</typeparam>
        /// <param name="map">A mapping function for branch T0 value.</param>
        /// <returns>A task that produces union with mapped branch T0 or original value from another branch.</returns>
        public async UniTask<OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>> MapT0Async<TOut0>(Func<T0, UniTask<TOut0>> map)
        {
            return IsT0 ? new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(await map(AsT0)) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T1 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut1">Type of mapped branch T1.</typeparam>
        /// <param name="map">A mapping function for branch T1 value.</param>
        /// <returns>A union with mapped branch T1 or original value from another branch.</returns>
        public OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7> MapT1<TOut1>(Func<T1, TOut1> map)
        {
            return IsT1 ? new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(map(AsT1)) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT0),
                2 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T1 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut1">Type of mapped branch T1.</typeparam>
        /// <param name="map">A mapping function for branch T1 value.</param>
        /// <returns>A task that produces union with mapped branch T1 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>> MapT1Async<TOut1>(Func<T1, UniTask<TOut1>> map)
        {
            return IsT1 ? new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(await map(AsT1)) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT0),
                2 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T2 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut2">Type of mapped branch T2.</typeparam>
        /// <param name="map">A mapping function for branch T2 value.</param>
        /// <returns>A union with mapped branch T2 or original value from another branch.</returns>
        public OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7> MapT2<TOut2>(Func<T2, TOut2> map)
        {
            return IsT2 ? new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(map(AsT2)) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT1),
                3 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T2 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut2">Type of mapped branch T2.</typeparam>
        /// <param name="map">A mapping function for branch T2 value.</param>
        /// <returns>A task that produces union with mapped branch T2 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>> MapT2Async<TOut2>(Func<T2, UniTask<TOut2>> map)
        {
            return IsT2 ? new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(await map(AsT2)) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT1),
                3 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T3 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut3">Type of mapped branch T3.</typeparam>
        /// <param name="map">A mapping function for branch T3 value.</param>
        /// <returns>A union with mapped branch T3 or original value from another branch.</returns>
        public OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7> MapT3<TOut3>(Func<T3, TOut3> map)
        {
            return IsT3 ? new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(map(AsT3)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT2),
                4 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T3 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut3">Type of mapped branch T3.</typeparam>
        /// <param name="map">A mapping function for branch T3 value.</param>
        /// <returns>A task that produces union with mapped branch T3 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>> MapT3Async<TOut3>(Func<T3, UniTask<TOut3>> map)
        {
            return IsT3 ? new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(await map(AsT3)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT2),
                4 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T4 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut4">Type of mapped branch T4.</typeparam>
        /// <param name="map">A mapping function for branch T4 value.</param>
        /// <returns>A union with mapped branch T4 or original value from another branch.</returns>
        public OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7> MapT4<TOut4>(Func<T4, TOut4> map)
        {
            return IsT4 ? new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(map(AsT4)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT3),
                5 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T4 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut4">Type of mapped branch T4.</typeparam>
        /// <param name="map">A mapping function for branch T4 value.</param>
        /// <returns>A task that produces union with mapped branch T4 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>> MapT4Async<TOut4>(Func<T4, UniTask<TOut4>> map)
        {
            return IsT4 ? new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(await map(AsT4)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT3),
                5 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T5 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut5">Type of mapped branch T5.</typeparam>
        /// <param name="map">A mapping function for branch T5 value.</param>
        /// <returns>A union with mapped branch T5 or original value from another branch.</returns>
        public OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7> MapT5<TOut5>(Func<T5, TOut5> map)
        {
            return IsT5 ? new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(map(AsT5)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT4),
                6 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T5 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut5">Type of mapped branch T5.</typeparam>
        /// <param name="map">A mapping function for branch T5 value.</param>
        /// <returns>A task that produces union with mapped branch T5 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>> MapT5Async<TOut5>(Func<T5, UniTask<TOut5>> map)
        {
            return IsT5 ? new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(await map(AsT5)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT4),
                6 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T6 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut6">Type of mapped branch T6.</typeparam>
        /// <param name="map">A mapping function for branch T6 value.</param>
        /// <returns>A union with mapped branch T6 or original value from another branch.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7> MapT6<TOut6>(Func<T6, TOut6> map)
        {
            return IsT6 ? new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(map(AsT6)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT5),
                7 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T6 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut6">Type of mapped branch T6.</typeparam>
        /// <param name="map">A mapping function for branch T6 value.</param>
        /// <returns>A task that produces union with mapped branch T6 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>> MapT6Async<TOut6>(Func<T6, UniTask<TOut6>> map)
        {
            return IsT6 ? new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(await map(AsT6)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT5),
                7 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T7 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut7">Type of mapped branch T7.</typeparam>
        /// <param name="map">A mapping function for branch T7 value.</param>
        /// <returns>A union with mapped branch T7 or original value from another branch.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7> MapT7<TOut7>(Func<T7, TOut7> map)
        {
            return IsT7 ? new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(map(AsT7)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT6),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T7 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut7">Type of mapped branch T7.</typeparam>
        /// <param name="map">A mapping function for branch T7 value.</param>
        /// <returns>A task that produces union with mapped branch T7 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>> MapT7Async<TOut7>(Func<T7, UniTask<TOut7>> map)
        {
            return IsT7 ? new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(await map(AsT7)) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT6),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes action for active branch.
        /// </summary>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <param name="map3">An action for branch T3 value.</param>
        /// <param name="map4">An action for branch T4 value.</param>
        /// <param name="map5">An action for branch T5 value.</param>
        /// <param name="map6">An action for branch T6 value.</param>
        /// <param name="map7">An action for branch T7 value.</param>
        public void Switch(
            Action<T0> map0,
            Action<T1> map1,
            Action<T2> map2,
            Action<T3> map3,
            Action<T4> map4,
            Action<T5> map5,
            Action<T6> map6,
            Action<T7> map7
        )
        {
            if (IsT0)
            {
                map0(AsT0);
                return;
            }

            if (IsT1)
            {
                map1(AsT1);
                return;
            }

            if (IsT2)
            {
                map2(AsT2);
                return;
            }

            if (IsT3)
            {
                map3(AsT3);
                return;
            }

            if (IsT4)
            {
                map4(AsT4);
                return;
            }

            if (IsT5)
            {
                map5(AsT5);
                return;
            }

            if (IsT6)
            {
                map6(AsT6);
                return;
            }

            if (IsT7)
            {
                map7(AsT7);
                return;
            }

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes action for active branch and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to selected action.</param>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <param name="map3">An action for branch T3 value.</param>
        /// <param name="map4">An action for branch T4 value.</param>
        /// <param name="map5">An action for branch T5 value.</param>
        /// <param name="map6">An action for branch T6 value.</param>
        /// <param name="map7">An action for branch T7 value.</param>
        public void Switch<TContext>(
            TContext context,
            Action<TContext, T0> map0,
            Action<TContext, T1> map1,
            Action<TContext, T2> map2,
            Action<TContext, T3> map3,
            Action<TContext, T4> map4,
            Action<TContext, T5> map5,
            Action<TContext, T6> map6,
            Action<TContext, T7> map7
        )
        {
            if (IsT0)
            {
                map0(context, AsT0);
                return;
            }

            if (IsT1)
            {
                map1(context, AsT1);
                return;
            }

            if (IsT2)
            {
                map2(context, AsT2);
                return;
            }

            if (IsT3)
            {
                map3(context, AsT3);
                return;
            }

            if (IsT4)
            {
                map4(context, AsT4);
                return;
            }

            if (IsT5)
            {
                map5(context, AsT5);
                return;
            }

            if (IsT6)
            {
                map6(context, AsT6);
                return;
            }

            if (IsT7)
            {
                map7(context, AsT7);
                return;
            }

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes asynchronous action for active branch.
        /// </summary>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <param name="map3">An action for branch T3 value.</param>
        /// <param name="map4">An action for branch T4 value.</param>
        /// <param name="map5">An action for branch T5 value.</param>
        /// <param name="map6">An action for branch T6 value.</param>
        /// <param name="map7">An action for branch T7 value.</param>
        /// <returns>A task that completes when selected action finishes.</returns>
        public UniTask SwitchAsync(
            Func<T0, UniTask> map0,
            Func<T1, UniTask> map1,
            Func<T2, UniTask> map2,
            Func<T3, UniTask> map3,
            Func<T4, UniTask> map4,
            Func<T5, UniTask> map5,
            Func<T6, UniTask> map6,
            Func<T7, UniTask> map7
        )
        {
            if (IsT0)
                return map0(AsT0);

            if (IsT1)
                return map1(AsT1);

            if (IsT2)
                return map2(AsT2);

            if (IsT3)
                return map3(AsT3);

            if (IsT4)
                return map4(AsT4);

            if (IsT5)
                return map5(AsT5);

            if (IsT6)
                return map6(AsT6);

            if (IsT7)
                return map7(AsT7);

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes asynchronous action for active branch and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to selected action.</param>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <param name="map3">An action for branch T3 value.</param>
        /// <param name="map4">An action for branch T4 value.</param>
        /// <param name="map5">An action for branch T5 value.</param>
        /// <param name="map6">An action for branch T6 value.</param>
        /// <param name="map7">An action for branch T7 value.</param>
        /// <returns>A task that completes when selected action finishes.</returns>
        public UniTask SwitchAsync<TContext>(
            TContext context,
            Func<TContext, T0, UniTask> map0,
            Func<TContext, T1, UniTask> map1,
            Func<TContext, T2, UniTask> map2,
            Func<TContext, T3, UniTask> map3,
            Func<TContext, T4, UniTask> map4,
            Func<TContext, T5, UniTask> map5,
            Func<TContext, T6, UniTask> map6,
            Func<TContext, T7, UniTask> map7
        )
        {
            if (IsT0)
                return map0(context, AsT0);

            if (IsT1)
                return map1(context, AsT1);

            if (IsT2)
                return map2(context, AsT2);

            if (IsT3)
                return map3(context, AsT3);

            if (IsT4)
                return map4(context, AsT4);

            if (IsT5)
                return map5(context, AsT5);

            if (IsT6)
                return map6(context, AsT6);

            if (IsT7)
                return map7(context, AsT7);

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes side effect for branch T0 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT0(Action<T0> tap)
        {
            if (IsT0)
                tap(AsT0);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T0 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT0<TContext>(TContext context, Action<TContext, T0> tap)
        {
            if (IsT0)
                tap(context, AsT0);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T0 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT0Async(Func<T0, UniTask> tap)
        {
            if (IsT0)
                await tap(AsT0);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T0 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT0Async<TContext>(TContext context, Func<TContext, T0, UniTask> tap)
        {
            if (IsT0)
                await tap(context, AsT0);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T0.
        /// </summary>
        /// <typeparam name="TOut0">Type of chained branch T0.</typeparam>
        /// <param name="binder">A function that produces next union from branch T0 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7> BindT0<TOut0>(Func<T0, OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT0 ? binder(AsT0) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T0 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut0">Type of chained branch T0.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T0 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7> BindT0<TContext, TOut0>(TContext context, Func<TContext, T0, OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT0 ? binder(context, AsT0) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<TOut0, T1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T1 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT1(Action<T1> tap)
        {
            if (IsT1)
                tap(AsT1);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T1 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT1<TContext>(TContext context, Action<TContext, T1> tap)
        {
            if (IsT1)
                tap(context, AsT1);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T1 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT1Async(Func<T1, UniTask> tap)
        {
            if (IsT1)
                await tap(AsT1);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T1 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT1Async<TContext>(TContext context, Func<TContext, T1, UniTask> tap)
        {
            if (IsT1)
                await tap(context, AsT1);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T1.
        /// </summary>
        /// <typeparam name="TOut1">Type of chained branch T1.</typeparam>
        /// <param name="binder">A function that produces next union from branch T1 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7> BindT1<TOut1>(Func<T1, OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT1 ? binder(AsT1) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT0),
                2 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T1 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut1">Type of chained branch T1.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T1 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7> BindT1<TContext, TOut1>(TContext context, Func<TContext, T1, OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT1 ? binder(context, AsT1) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT0),
                2 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, TOut1, T2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T2 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT2(Action<T2> tap)
        {
            if (IsT2)
                tap(AsT2);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T2 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT2<TContext>(TContext context, Action<TContext, T2> tap)
        {
            if (IsT2)
                tap(context, AsT2);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T2 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT2Async(Func<T2, UniTask> tap)
        {
            if (IsT2)
                await tap(AsT2);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T2 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT2Async<TContext>(TContext context, Func<TContext, T2, UniTask> tap)
        {
            if (IsT2)
                await tap(context, AsT2);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T2.
        /// </summary>
        /// <typeparam name="TOut2">Type of chained branch T2.</typeparam>
        /// <param name="binder">A function that produces next union from branch T2 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7> BindT2<TOut2>(Func<T2, OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT2 ? binder(AsT2) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT1),
                3 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T2 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut2">Type of chained branch T2.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T2 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7> BindT2<TContext, TOut2>(TContext context, Func<TContext, T2, OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>> binder)
        {
            return IsT2 ? binder(context, AsT2) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT1),
                3 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, TOut2, T3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T3 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T3 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT3(Action<T3> tap)
        {
            if (IsT3)
                tap(AsT3);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T3 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T3 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT3<TContext>(TContext context, Action<TContext, T3> tap)
        {
            if (IsT3)
                tap(context, AsT3);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T3 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T3 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT3Async(Func<T3, UniTask> tap)
        {
            if (IsT3)
                await tap(AsT3);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T3 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T3 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT3Async<TContext>(TContext context, Func<TContext, T3, UniTask> tap)
        {
            if (IsT3)
                await tap(context, AsT3);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T3.
        /// </summary>
        /// <typeparam name="TOut3">Type of chained branch T3.</typeparam>
        /// <param name="binder">A function that produces next union from branch T3 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7> BindT3<TOut3>(Func<T3, OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>> binder)
        {
            return IsT3 ? binder(AsT3) : _index switch
            {
                0 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT2),
                4 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T3 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut3">Type of chained branch T3.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T3 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7> BindT3<TContext, TOut3>(TContext context, Func<TContext, T3, OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>> binder)
        {
            return IsT3 ? binder(context, AsT3) : _index switch
            {
                0 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT2),
                4 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, TOut3, T4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T4 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T4 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT4(Action<T4> tap)
        {
            if (IsT4)
                tap(AsT4);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T4 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T4 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT4<TContext>(TContext context, Action<TContext, T4> tap)
        {
            if (IsT4)
                tap(context, AsT4);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T4 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T4 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT4Async(Func<T4, UniTask> tap)
        {
            if (IsT4)
                await tap(AsT4);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T4 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T4 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT4Async<TContext>(TContext context, Func<TContext, T4, UniTask> tap)
        {
            if (IsT4)
                await tap(context, AsT4);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T4.
        /// </summary>
        /// <typeparam name="TOut4">Type of chained branch T4.</typeparam>
        /// <param name="binder">A function that produces next union from branch T4 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7> BindT4<TOut4>(Func<T4, OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>> binder)
        {
            return IsT4 ? binder(AsT4) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT3),
                5 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T4 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut4">Type of chained branch T4.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T4 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7> BindT4<TContext, TOut4>(TContext context, Func<TContext, T4, OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>> binder)
        {
            return IsT4 ? binder(context, AsT4) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT3),
                5 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, TOut4, T5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T5 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T5 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT5(Action<T5> tap)
        {
            if (IsT5)
                tap(AsT5);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T5 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T5 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT5<TContext>(TContext context, Action<TContext, T5> tap)
        {
            if (IsT5)
                tap(context, AsT5);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T5 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T5 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT5Async(Func<T5, UniTask> tap)
        {
            if (IsT5)
                await tap(AsT5);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T5 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T5 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT5Async<TContext>(TContext context, Func<TContext, T5, UniTask> tap)
        {
            if (IsT5)
                await tap(context, AsT5);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T5.
        /// </summary>
        /// <typeparam name="TOut5">Type of chained branch T5.</typeparam>
        /// <param name="binder">A function that produces next union from branch T5 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7> BindT5<TOut5>(Func<T5, OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>> binder)
        {
            return IsT5 ? binder(AsT5) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT4),
                6 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T5 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut5">Type of chained branch T5.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T5 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7> BindT5<TContext, TOut5>(TContext context, Func<TContext, T5, OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>> binder)
        {
            return IsT5 ? binder(context, AsT5) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT4),
                6 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT6),
                7 => new OneOf<T0, T1, T2, T3, T4, TOut5, T6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T6 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T6 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT6(Action<T6> tap)
        {
            if (IsT6)
                tap(AsT6);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T6 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T6 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT6<TContext>(TContext context, Action<TContext, T6> tap)
        {
            if (IsT6)
                tap(context, AsT6);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T6 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T6 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT6Async(Func<T6, UniTask> tap)
        {
            if (IsT6)
                await tap(AsT6);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T6 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T6 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT6Async<TContext>(TContext context, Func<TContext, T6, UniTask> tap)
        {
            if (IsT6)
                await tap(context, AsT6);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T6.
        /// </summary>
        /// <typeparam name="TOut6">Type of chained branch T6.</typeparam>
        /// <param name="binder">A function that produces next union from branch T6 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7> BindT6<TOut6>(Func<T6, OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>> binder)
        {
            return IsT6 ? binder(AsT6) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT5),
                7 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T6 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut6">Type of chained branch T6.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T6 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7> BindT6<TContext, TOut6>(TContext context, Func<TContext, T6, OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>> binder)
        {
            return IsT6 ? binder(context, AsT6) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT5),
                7 => new OneOf<T0, T1, T2, T3, T4, T5, TOut6, T7>(AsT7),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T7 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T7 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT7(Action<T7> tap)
        {
            if (IsT7)
                tap(AsT7);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T7 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T7 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, T7> TapT7<TContext>(TContext context, Action<TContext, T7> tap)
        {
            if (IsT7)
                tap(context, AsT7);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T7 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T7 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT7Async(Func<T7, UniTask> tap)
        {
            if (IsT7)
                await tap(AsT7);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T7 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T7 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2, T3, T4, T5, T6, T7>> TapT7Async<TContext>(TContext context, Func<TContext, T7, UniTask> tap)
        {
            if (IsT7)
                await tap(context, AsT7);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T7.
        /// </summary>
        /// <typeparam name="TOut7">Type of chained branch T7.</typeparam>
        /// <param name="binder">A function that produces next union from branch T7 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7> BindT7<TOut7>(Func<T7, OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>> binder)
        {
            return IsT7 ? binder(AsT7) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT6),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T7 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut7">Type of chained branch T7.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T7 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7> BindT7<TContext, TOut7>(TContext context, Func<TContext, T7, OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>> binder)
        {
            return IsT7 ? binder(context, AsT7) : _index switch
            {
                0 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT0),
                1 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT1),
                2 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT2),
                3 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT3),
                4 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT4),
                5 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT5),
                6 => new OneOf<T0, T1, T2, T3, T4, T5, T6, TOut7>(AsT6),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Determines whether current union equals specified union.
        /// </summary>
        /// <param name="other">A union to compare with current union.</param>
        /// <returns><see langword="true" /> if current union equals <paramref name="other" />; otherwise, <see langword="false" />.</returns>
        public bool Equals(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> other)
        {
            if (_hasValue != other._hasValue || _index != other._index)
                return false;

            return _index switch
            {
                0 => EqualityComparer<T0>.Default.Equals(AsT0, other.AsT0),
                1 => EqualityComparer<T1>.Default.Equals(AsT1, other.AsT1),
                2 => EqualityComparer<T2>.Default.Equals(AsT2, other.AsT2),
                3 => EqualityComparer<T3>.Default.Equals(AsT3, other.AsT3),
                4 => EqualityComparer<T4>.Default.Equals(AsT4, other.AsT4),
                5 => EqualityComparer<T5>.Default.Equals(AsT5, other.AsT5),
                6 => EqualityComparer<T6>.Default.Equals(AsT6, other.AsT6),
                7 => EqualityComparer<T7>.Default.Equals(AsT7, other.AsT7),
                _ => false
            };
        }

        /// <summary>
        /// Determines whether current union equals specified object.
        /// </summary>
        /// <param name="obj">An object to compare with current union.</param>
        /// <returns><see langword="true" /> if <paramref name="obj" /> is equal to current union; otherwise, <see langword="false" />.</returns>
        public override bool Equals(object obj) => obj is OneOf<T0, T1, T2, T3, T4, T5, T6, T7> other && Equals(other);

        /// <summary>
        /// Serves as hash function for current union.
        /// </summary>
        /// <returns>A hash code for current union.</returns>
        public override int GetHashCode()
        {
            return _index switch
            {
                0 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T0>.Default.GetHashCode(AsT0)),
                1 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T1>.Default.GetHashCode(AsT1)),
                2 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T2>.Default.GetHashCode(AsT2)),
                3 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T3>.Default.GetHashCode(AsT3)),
                4 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T4>.Default.GetHashCode(AsT4)),
                5 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T5>.Default.GetHashCode(AsT5)),
                6 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T6>.Default.GetHashCode(AsT6)),
                7 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T7>.Default.GetHashCode(AsT7)),
                _ => HashCode.Combine(_hasValue, _index)
            };
        }

        /// <summary>
        /// Returns string representation of current union.
        /// </summary>
        /// <returns>A string that identifies active branch and stored value.</returns>
        public override string ToString()
        {
            return _index switch
            {
                0 => $"T0({AsT0})",
                1 => $"T1({AsT1})",
                2 => $"T2({AsT2})",
                3 => $"T3({AsT3})",
                4 => $"T4({AsT4})",
                5 => $"T5({AsT5})",
                6 => $"T6({AsT6})",
                7 => $"T7({AsT7})",
                _ => $"{nameof(OneOf<T0, T1, T2, T3, T4, T5, T6, T7>)}(Invalid)"
            };
        }

        private static InvalidOperationException CreateWrongBranchException(string branchName)
            => new InvalidOperationException($"OneOf does not contain a value of type {branchName}.");

        private static ArgumentOutOfRangeException CreateInvalidStateException()
            => new ArgumentOutOfRangeException(nameof(OneOf<T0, T1, T2, T3, T4, T5, T6, T7>), "OneOf is in an invalid state.");

        /// <summary>
        /// Determines whether two unions are equal.
        /// </summary>
        /// <param name="left">A union to compare.</param>
        /// <param name="right">A union to compare.</param>
        /// <returns><see langword="true" /> if <paramref name="left" /> equals <paramref name="right" />; otherwise, <see langword="false" />.</returns>
        public static bool operator ==(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> left, OneOf<T0, T1, T2, T3, T4, T5, T6, T7> right) => left.Equals(right);

        /// <summary>
        /// Determines whether two unions are not equal.
        /// </summary>
        /// <param name="left">A union to compare.</param>
        /// <param name="right">A union to compare.</param>
        /// <returns><see langword="true" /> if <paramref name="left" /> does not equal <paramref name="right" />; otherwise, <see langword="false" />.</returns>
        public static bool operator !=(OneOf<T0, T1, T2, T3, T4, T5, T6, T7> left, OneOf<T0, T1, T2, T3, T4, T5, T6, T7> right) => !left.Equals(right);
    }
}
