#!/usr/bin/env python3

import argparse
from pathlib import Path


AUTO_GENERATED_HEADER = """// <auto-generated>
// This file was generated automatically by Tools/CodeGen/GenerateOneOf.py.
// </auto-generated>
"""


def format_type_params(arity: int) -> str:
    return ", ".join(f"T{i}" for i in range(arity))


def format_union_type(arity: int) -> str:
    return f"OneOf<{format_type_params(arity)}>"


def format_replaced_union_type(arity: int, index: int, replacement: str) -> str:
    type_args = [replacement if i == index else f"T{i}" for i in range(arity)]
    return f"OneOf<{', '.join(type_args)}>"


def indent(text: str, level: int) -> str:
    prefix = " " * (level * 4)
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def build_runtime_code(arity: int) -> str:
    type_params = format_type_params(arity)
    union_type = format_union_type(arity)
    lines: list[str] = [
        AUTO_GENERATED_HEADER.rstrip(),
        "using System;",
        "using System.Collections.Generic;",
        "using Cysharp.Threading.Tasks;",
        "",
        "namespace Unicore.Monads",
        "{",
        "    /// <summary>",
        f"    /// Represents discriminated union that contains one value of types <typeparamref name=\"T0\" /> through <typeparamref name=\"T{arity - 1}\" />.",
        "    /// </summary>",
    ]

    for i in range(arity):
        lines.append(f"    /// <typeparam name=\"T{i}\">Type of branch {i}.</typeparam>")

    lines.extend([
        f"    public readonly struct OneOf<{type_params}> : IEquatable<OneOf<{type_params}>>",
        "    {",
        "        private readonly object _value;",
        "        private readonly byte _index;",
        "        private readonly bool _hasValue;",
        "",
    ])

    for i in range(arity):
        lines.extend([
            "        /// <summary>",
            f"        /// Gets branch T{i} value.",
            "        /// </summary>",
            f"        /// <value>A value stored in branch T{i}.</value>",
            f"        /// <exception cref=\"InvalidOperationException\">Current value is not stored in branch T{i}.</exception>",
            f"        public T{i} AsT{i} => _hasValue",
            f"            ? _index == {i}",
            f"                ? (T{i})_value",
            f"                : throw CreateWrongBranchException(\"T{i}\")",
            "            : throw CreateInvalidStateException();",
            "",
            "        /// <summary>",
            f"        /// Gets a value that indicates whether current value is stored in branch T{i}.",
            "        /// </summary>",
            f"        /// <value><see langword=\"true\" /> if current value is stored in branch T{i}; otherwise, <see langword=\"false\" />.</value>",
            f"        public bool IsT{i} => _index == {i};",
            "",
            "        /// <summary>",
            f"        /// Initializes a new instance of the <see cref=\"OneOf{{{type_params}}}\" /> struct with branch T{i} value.",
            "        /// </summary>",
            f"        /// <param name=\"value\">A value to store in branch T{i}.</param>",
            f"        public OneOf(T{i} value)",
            "        {",
            "            _value = value;",
            f"            _index = {i};",
            "            _hasValue = true;",
            "        }",
            "",
        ])

    map_params = ",\n".join(f"            Func<T{i}, TReturn> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Projects current union into another value by selecting mapper for active branch.",
        "        /// </summary>",
        "        /// <typeparam name=\"TReturn\">Type of mapped value.</typeparam>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">A mapping function for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A mapped value produced by selected mapper.</returns>",
        "        public TReturn Map<TReturn>(",
        map_params,
        "        )",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => map{i}(AsT{i}),")
    lines.extend([
        "                _ => throw CreateInvalidStateException()",
        "            };",
        "        }",
        "",
    ])

    map_ctx_params = ",\n".join(f"            Func<TContext, T{i}, TReturn> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Projects current union into another value by selecting mapper for active branch and passing shared context.",
        "        /// </summary>",
        "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
        "        /// <typeparam name=\"TReturn\">Type of mapped value.</typeparam>",
        "        /// <param name=\"context\">A context value passed to selected mapper.</param>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">A mapping function for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A mapped value produced by selected mapper.</returns>",
        "        public TReturn Map<TContext, TReturn>(",
        "            TContext context,",
        map_ctx_params,
        "        )",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => map{i}(context, AsT{i}),")
    lines.extend([
        "                _ => throw CreateInvalidStateException()",
        "            };",
        "        }",
        "",
    ])

    map_async_params = ",\n".join(f"            Func<T{i}, UniTask<TReturn>> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Projects current union into another value asynchronously by selecting mapper for active branch.",
        "        /// </summary>",
        "        /// <typeparam name=\"TReturn\">Type of mapped value.</typeparam>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">A mapping function for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A task that produces mapped value from selected mapper.</returns>",
        "        public UniTask<TReturn> MapAsync<TReturn>(",
        map_async_params,
        "        )",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => map{i}(AsT{i}),")
    lines.extend([
        "                _ => throw CreateInvalidStateException()",
        "            };",
        "        }",
        "",
    ])

    map_async_ctx_params = ",\n".join(f"            Func<TContext, T{i}, UniTask<TReturn>> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Projects current union into another value asynchronously by selecting mapper for active branch and passing shared context.",
        "        /// </summary>",
        "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
        "        /// <typeparam name=\"TReturn\">Type of mapped value.</typeparam>",
        "        /// <param name=\"context\">A context value passed to selected mapper.</param>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">A mapping function for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A task that produces mapped value from selected mapper.</returns>",
        "        public UniTask<TReturn> MapAsync<TContext, TReturn>(",
        "            TContext context,",
        map_async_ctx_params,
        "        )",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => map{i}(context, AsT{i}),")
    lines.extend([
        "                _ => throw CreateInvalidStateException()",
        "            };",
        "        }",
        "",
    ])

    for i in range(arity):
        lines.extend([
            "        /// <summary>",
            f"        /// Gets branch T{i} value when current union stores it.",
            "        /// </summary>",
            f"        /// <param name=\"value\">When this method returns, contains branch T{i} value if it exists; otherwise, the default value of <typeparamref name=\"T{i}\" />. This parameter is treated as uninitialized.</param>",
            f"        /// <returns><see langword=\"true\" /> if current value is stored in branch T{i}; otherwise, <see langword=\"false\" />.</returns>",
            f"        public bool TryGetT{i}(out T{i} value)",
            "        {",
            f"            if (IsT{i})",
            "            {",
            f"                value = AsT{i};",
            "                return true;",
            "            }",
            "",
            "            value = default;",
            "            return false;",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Gets branch T{i} value or provided fallback when current union stores another branch.",
            "        /// </summary>",
            "        /// <param name=\"defaultValue\">A fallback value.</param>",
            f"        /// <returns>A branch T{i} value or <paramref name=\"defaultValue\" />.</returns>",
            f"        public T{i} GetT{i}OrDefault(T{i} defaultValue = default) => IsT{i} ? AsT{i} : defaultValue;",
            "",
        ])

    for i in range(arity):
        mapped_union = format_replaced_union_type(arity, i, f"TOut{i}")
        lines.extend([
            "        /// <summary>",
            f"        /// Projects branch T{i} into another branch type and preserves all other branches unchanged.",
            "        /// </summary>",
            f"        /// <typeparam name=\"TOut{i}\">Type of mapped branch T{i}.</typeparam>",
            f"        /// <param name=\"map\">A mapping function for branch T{i} value.</param>",
            f"        /// <returns>A union with mapped branch T{i} or original value from another branch.</returns>",
            f"        public {mapped_union} MapT{i}<TOut{i}>(Func<T{i}, TOut{i}> map)",
            "        {",
            f"            return IsT{i} ? new {mapped_union}(map(AsT{i})) : _index switch",
            "            {",
        ])
        for j in range(arity):
            if j == i:
                continue
            lines.append(f"                {j} => new {mapped_union}(AsT{j}),")
        lines.extend([
            "                _ => throw CreateInvalidStateException()",
            "            };",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Projects branch T{i} into another branch type asynchronously and preserves all other branches unchanged.",
            "        /// </summary>",
            f"        /// <typeparam name=\"TOut{i}\">Type of mapped branch T{i}.</typeparam>",
            f"        /// <param name=\"map\">A mapping function for branch T{i} value.</param>",
            f"        /// <returns>A task that produces union with mapped branch T{i} or original value from another branch.</returns>",
            f"        public async UniTask<{mapped_union}> MapT{i}Async<TOut{i}>(Func<T{i}, UniTask<TOut{i}>> map)",
            "        {",
            f"            return IsT{i} ? new {mapped_union}(await map(AsT{i})) : _index switch",
            "            {",
        ])
        for j in range(arity):
            if j == i:
                continue
            lines.append(f"                {j} => new {mapped_union}(AsT{j}),")
        lines.extend([
            "                _ => throw CreateInvalidStateException()",
            "            };",
            "        }",
            "",
        ])

    switch_params = ",\n".join(f"            Action<T{i}> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Executes action for active branch.",
        "        /// </summary>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">An action for branch T{i} value.</param>")
    lines.extend([
        "        public void Switch(",
        switch_params,
        "        )",
        "        {",
    ])
    for i in range(arity):
        lines.extend([
            f"            if (IsT{i})",
            "            {",
            f"                map{i}(AsT{i});",
            "                return;",
            "            }",
            "",
        ])
    lines.extend([
        "            throw CreateInvalidStateException();",
        "        }",
        "",
    ])

    switch_ctx_params = ",\n".join(f"            Action<TContext, T{i}> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Executes action for active branch and passes shared context.",
        "        /// </summary>",
        "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
        "        /// <param name=\"context\">A context value passed to selected action.</param>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">An action for branch T{i} value.</param>")
    lines.extend([
        "        public void Switch<TContext>(",
        "            TContext context,",
        switch_ctx_params,
        "        )",
        "        {",
    ])
    for i in range(arity):
        lines.extend([
            f"            if (IsT{i})",
            "            {",
            f"                map{i}(context, AsT{i});",
            "                return;",
            "            }",
            "",
        ])
    lines.extend([
        "            throw CreateInvalidStateException();",
        "        }",
        "",
    ])

    switch_async_params = ",\n".join(f"            Func<T{i}, UniTask> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Executes asynchronous action for active branch.",
        "        /// </summary>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">An action for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A task that completes when selected action finishes.</returns>",
        "        public UniTask SwitchAsync(",
        switch_async_params,
        "        )",
        "        {",
    ])
    for i in range(arity):
        lines.extend([
            f"            if (IsT{i})",
            f"                return map{i}(AsT{i});",
            "",
        ])
    lines.extend([
        "            throw CreateInvalidStateException();",
        "        }",
        "",
    ])

    switch_async_ctx_params = ",\n".join(f"            Func<TContext, T{i}, UniTask> map{i}" for i in range(arity))
    lines.extend([
        "        /// <summary>",
        "        /// Executes asynchronous action for active branch and passes shared context.",
        "        /// </summary>",
        "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
        "        /// <param name=\"context\">A context value passed to selected action.</param>",
    ])
    for i in range(arity):
        lines.append(f"        /// <param name=\"map{i}\">An action for branch T{i} value.</param>")
    lines.extend([
        "        /// <returns>A task that completes when selected action finishes.</returns>",
        "        public UniTask SwitchAsync<TContext>(",
        "            TContext context,",
        switch_async_ctx_params,
        "        )",
        "        {",
    ])
    for i in range(arity):
        lines.extend([
            f"            if (IsT{i})",
            f"                return map{i}(context, AsT{i});",
            "",
        ])
    lines.extend([
        "            throw CreateInvalidStateException();",
        "        }",
        "",
    ])

    for i in range(arity):
        mapped_union = union_type
        bind_union = format_replaced_union_type(arity, i, f"TOut{i}")
        lines.extend([
            "        /// <summary>",
            f"        /// Executes side effect for branch T{i} and returns current union.",
            "        /// </summary>",
            f"        /// <param name=\"tap\">An action for branch T{i} value.</param>",
            "        /// <returns>Current union value.</returns>",
            f"        public {mapped_union} TapT{i}(Action<T{i}> tap)",
            "        {",
            f"            if (IsT{i})",
            f"                tap(AsT{i});",
            "",
            "            return this;",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Executes side effect for branch T{i} with shared context and returns current union.",
            "        /// </summary>",
            "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
            "        /// <param name=\"context\">A context value passed to <paramref name=\"tap\" />.</param>",
            f"        /// <param name=\"tap\">An action for branch T{i} value.</param>",
            "        /// <returns>Current union value.</returns>",
            f"        public {mapped_union} TapT{i}<TContext>(TContext context, Action<TContext, T{i}> tap)",
            "        {",
            f"            if (IsT{i})",
            f"                tap(context, AsT{i});",
            "",
            "            return this;",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Executes asynchronous side effect for branch T{i} and returns current union.",
            "        /// </summary>",
            f"        /// <param name=\"tap\">An action for branch T{i} value.</param>",
            "        /// <returns>A task that produces current union value.</returns>",
            f"        public async UniTask<{mapped_union}> TapT{i}Async(Func<T{i}, UniTask> tap)",
            "        {",
            f"            if (IsT{i})",
            f"                await tap(AsT{i});",
            "",
            "            return this;",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Executes asynchronous side effect for branch T{i} with shared context and returns current union.",
            "        /// </summary>",
            "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
            "        /// <param name=\"context\">A context value passed to <paramref name=\"tap\" />.</param>",
            f"        /// <param name=\"tap\">An action for branch T{i} value.</param>",
            "        /// <returns>A task that produces current union value.</returns>",
            f"        public async UniTask<{mapped_union}> TapT{i}Async<TContext>(TContext context, Func<TContext, T{i}, UniTask> tap)",
            "        {",
            f"            if (IsT{i})",
            f"                await tap(context, AsT{i});",
            "",
            "            return this;",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Chains another union-producing operation that runs only for branch T{i}.",
            "        /// </summary>",
            f"        /// <typeparam name=\"TOut{i}\">Type of chained branch T{i}.</typeparam>",
            f"        /// <param name=\"binder\">A function that produces next union from branch T{i} value.</param>",
            "        /// <returns>A chained union.</returns>",
            f"        public {bind_union} BindT{i}<TOut{i}>(Func<T{i}, {bind_union}> binder)",
            "        {",
            f"            return IsT{i} ? binder(AsT{i}) : _index switch",
            "            {",
        ])
        for j in range(arity):
            if j == i:
                continue
            lines.append(f"                {j} => new {bind_union}(AsT{j}),")
        lines.extend([
            "                _ => throw CreateInvalidStateException()",
            "            };",
            "        }",
            "",
            "        /// <summary>",
            f"        /// Chains another union-producing operation that runs only for branch T{i} and passes shared context.",
            "        /// </summary>",
            "        /// <typeparam name=\"TContext\">Type of shared context.</typeparam>",
            f"        /// <typeparam name=\"TOut{i}\">Type of chained branch T{i}.</typeparam>",
            "        /// <param name=\"context\">A context value passed to <paramref name=\"binder\" />.</param>",
            f"        /// <param name=\"binder\">A function that produces next union from branch T{i} value.</param>",
            "        /// <returns>A chained union.</returns>",
            f"        public {bind_union} BindT{i}<TContext, TOut{i}>(TContext context, Func<TContext, T{i}, {bind_union}> binder)",
            "        {",
            f"            return IsT{i} ? binder(context, AsT{i}) : _index switch",
            "            {",
        ])
        for j in range(arity):
            if j == i:
                continue
            lines.append(f"                {j} => new {bind_union}(AsT{j}),")
        lines.extend([
            "                _ => throw CreateInvalidStateException()",
            "            };",
            "        }",
            "",
        ])

    lines.extend([
        "        /// <summary>",
        "        /// Determines whether current union equals specified union.",
        "        /// </summary>",
        "        /// <param name=\"other\">A union to compare with current union.</param>",
        "        /// <returns><see langword=\"true\" /> if current union equals <paramref name=\"other\" />; otherwise, <see langword=\"false\" />.</returns>",
        f"        public bool Equals({union_type} other)",
        "        {",
        "            if (_hasValue != other._hasValue || _index != other._index)",
        "                return false;",
        "",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => EqualityComparer<T{i}>.Default.Equals(AsT{i}, other.AsT{i}),")
    lines.extend([
        "                _ => false",
        "            };",
        "        }",
        "",
        "        /// <summary>",
        "        /// Determines whether current union equals specified object.",
        "        /// </summary>",
        "        /// <param name=\"obj\">An object to compare with current union.</param>",
        "        /// <returns><see langword=\"true\" /> if <paramref name=\"obj\" /> is equal to current union; otherwise, <see langword=\"false\" />.</returns>",
        f"        public override bool Equals(object obj) => obj is {union_type} other && Equals(other);",
        "",
        "        /// <summary>",
        "        /// Serves as hash function for current union.",
        "        /// </summary>",
        "        /// <returns>A hash code for current union.</returns>",
        "        public override int GetHashCode()",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T{i}>.Default.GetHashCode(AsT{i})),")
    lines.extend([
        "                _ => HashCode.Combine(_hasValue, _index)",
        "            };",
        "        }",
        "",
        "        /// <summary>",
        "        /// Returns string representation of current union.",
        "        /// </summary>",
        "        /// <returns>A string that identifies active branch and stored value.</returns>",
        "        public override string ToString()",
        "        {",
        "            return _index switch",
        "            {",
    ])
    for i in range(arity):
        lines.append(f"                {i} => $\"T{i}({{AsT{i}}})\",")
    lines.extend([
        f"                _ => $\"{{nameof(OneOf<{type_params}>)}}(Invalid)\"",
        "            };",
        "        }",
        "",
        "        private static InvalidOperationException CreateWrongBranchException(string branchName)",
        "            => new InvalidOperationException($\"OneOf does not contain a value of type {branchName}.\");",
        "",
        "        private static ArgumentOutOfRangeException CreateInvalidStateException()",
        f"            => new ArgumentOutOfRangeException(nameof(OneOf<{type_params}>), \"OneOf is in an invalid state.\");",
        "",
        "        /// <summary>",
        "        /// Determines whether two unions are equal.",
        "        /// </summary>",
        "        /// <param name=\"left\">A union to compare.</param>",
        "        /// <param name=\"right\">A union to compare.</param>",
        "        /// <returns><see langword=\"true\" /> if <paramref name=\"left\" /> equals <paramref name=\"right\" />; otherwise, <see langword=\"false\" />.</returns>",
        f"        public static bool operator ==({union_type} left, {union_type} right) => left.Equals(right);",
        "",
        "        /// <summary>",
        "        /// Determines whether two unions are not equal.",
        "        /// </summary>",
        "        /// <param name=\"left\">A union to compare.</param>",
        "        /// <param name=\"right\">A union to compare.</param>",
        "        /// <returns><see langword=\"true\" /> if <paramref name=\"left\" /> does not equal <paramref name=\"right\" />; otherwise, <see langword=\"false\" />.</returns>",
        f"        public static bool operator !=({union_type} left, {union_type} right) => !left.Equals(right);",
        "    }",
        "}",
    ])

    return "\n".join(lines) + "\n"


def build_test_code(arity: int) -> str:
    branch_names = [f"Branch{i}" for i in range(arity)]
    mapped_names = [f"Mapped{i}" for i in range(arity)]

    lines: list[str] = [
        AUTO_GENERATED_HEADER.rstrip(),
        "using System;",
        "using System.Collections;",
        "using Cysharp.Threading.Tasks;",
        "using NUnit.Framework;",
        "using UnityEngine.TestTools;",
        "using Unicore.Monads;",
        "",
        "namespace Unicore.Tests",
        "{",
        "    [TestFixture]",
        f"    public sealed class OneOf{arity}Tests",
        "    {",
    ]

    for i in range(arity):
        lines.extend([
            f"        private sealed class {branch_names[i]}",
            "        {",
            f"            public {branch_names[i]}(string value) => Value = value;",
            "",
            "            public string Value { get; }",
            "",
            "            public override string ToString() => Value;",
            "        }",
            "",
            f"        private sealed class {mapped_names[i]}",
            "        {",
            f"            public {mapped_names[i]}(string value) => Value = value;",
            "",
            "            public string Value { get; }",
            "",
            "            public override string ToString() => Value;",
            "        }",
            "",
        ])

    lines.extend([
        "        [SetUp]",
        "        public void SetUp()",
        "        {",
        "            LogAssert.ignoreFailingMessages = false;",
        "        }",
        "",
        "        [TearDown]",
        "        public void TearDown()",
        "        {",
        "            LogAssert.NoUnexpectedReceived();",
        "            LogAssert.ignoreFailingMessages = false;",
        "        }",
        "",
    ])

    def runtime_union(types: list[str]) -> str:
        return f"OneOf<{', '.join(types)}>"

    union_type = runtime_union(branch_names)

    def type_list() -> list[str]:
        return branch_names[:]

    def ctor_expr(index: int, value_expr: str) -> str:
        return f"new {union_type}({value_expr})"

    def branch_var(index: int) -> str:
        return f"branch{index}"

    def branch_ctor_expr(index: int, value: str) -> str:
        return f"new {branch_names[index]}(\"{value}\")"

    for i in range(arity):
        next_index = (i + 1) % arity
        current_ctor = ctor_expr(i, branch_var(i))
        next_ctor = ctor_expr(next_index, branch_ctor_expr(next_index, f"other-{next_index}"))
        lines.extend([
            "        [Test]",
            f"        public void TryGetT{i}_OnT{i}_ReturnsTrueAndValue()",
            "        {",
            f"            var {branch_var(i)} = new {branch_names[i]}(\"branch-{i}\");",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var result = oneOf.TryGetT{i}(out var value);",
            "",
            "            Assert.That(result, Is.True);",
            f"            Assert.That(value, Is.SameAs({branch_var(i)}));",
            "        }",
            "",
            "        [Test]",
            f"        public void TryGetT{i}_OnT{next_index}_ReturnsFalseAndDefault()",
            "        {",
            f"            var oneOf = {next_ctor};",
            "",
            f"            var result = oneOf.TryGetT{i}(out var value);",
            "",
            "            Assert.That(result, Is.False);",
            "            Assert.That(value, Is.Null);",
            "        }",
            "",
            "        [Test]",
            f"        public void AsT{i}_OnT{next_index}_ThrowsInvalidOperationExceptionWithMessage()",
            "        {",
            f"            var oneOf = {next_ctor};",
            "",
            f"            var exception = Assert.Throws<InvalidOperationException>(() => _ = oneOf.AsT{i});",
            "",
            f"            Assert.That(exception!.Message, Is.EqualTo(\"OneOf does not contain a value of type T{i}.\"));",
            "        }",
            "",
            "        [Test]",
            f"        public void GetT{i}OrDefault_OnT{i}_ReturnsValue()",
            "        {",
            f"            var {branch_var(i)} = new {branch_names[i]}(\"branch-{i}\");",
            f"            var fallback = new {branch_names[i]}(\"fallback-{i}\");",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var value = oneOf.GetT{i}OrDefault(fallback);",
            "",
            f"            Assert.That(value, Is.SameAs({branch_var(i)}));",
            "        }",
            "",
            "        [Test]",
            f"        public void GetT{i}OrDefault_OnT{next_index}_ReturnsFallback()",
            "        {",
            f"            var fallback = new {branch_names[i]}(\"fallback-{i}\");",
            f"            var oneOf = {next_ctor};",
            "",
            f"            var value = oneOf.GetT{i}OrDefault(fallback);",
            "",
            "            Assert.That(value, Is.SameAs(fallback));",
            "        }",
            "",
        ])

    lines.extend([
        "        [Test]",
        "        public void Map_OnDefaultValue_ThrowsArgumentOutOfRangeExceptionWithMessage()",
        "        {",
        f"            var oneOf = default({union_type});",
        "",
        "            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => oneOf.Map(",
    ])
    for i in range(arity):
        suffix = "," if i < arity - 1 else "));"
        lines.append(f"                _ => \"mapped-{i}\"{suffix}")
    lines.extend([
        "",
        "            Assert.That(exception!.Message, Does.StartWith(\"OneOf is in an invalid state.\"));",
        "        }",
        "",
        "        [Test]",
        "        public void Switch_OnDefaultValue_ThrowsArgumentOutOfRangeExceptionWithMessage()",
        "        {",
        f"            var oneOf = default({union_type});",
        "",
        "            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => oneOf.Switch(",
    ])
    for i in range(arity):
        suffix = "," if i < arity - 1 else "));"
        lines.append(f"                _ => {{ }}{suffix}")
    lines.extend([
        "",
        "            Assert.That(exception!.Message, Does.StartWith(\"OneOf is in an invalid state.\"));",
        "        }",
        "",
    ])

    for i in range(arity):
        replacement_types = type_list()
        replacement_types[i] = mapped_names[i]
        mapped_union = runtime_union(replacement_types)
        next_index = (i + 1) % arity
        current_ctor = ctor_expr(i, branch_ctor_expr(i, f"branch-{i}"))
        next_ctor = ctor_expr(next_index, branch_ctor_expr(next_index, f"other-{next_index}"))
        lines.extend([
            "        [Test]",
            f"        public void MapT{i}_OnT{i}_MapsSelectedBranch()",
            "        {",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var mapped = oneOf.MapT{i}(value => new {mapped_names[i]}($\"mapped:{{value.Value}}\"));",
            "",
            f"            Assert.That(mapped.IsT{i}, Is.True);",
            f"            Assert.That(mapped.AsT{i}.Value, Is.EqualTo(\"mapped:branch-{i}\"));",
            "        }",
            "",
            "        [Test]",
            f"        public void MapT{i}_OnT{next_index}_PreservesOtherBranch()",
            "        {",
            "            var called = false;",
            f"            var oneOf = {next_ctor};",
            "",
            f"            var mapped = oneOf.MapT{i}(value =>",
            "            {",
            "                called = true;",
            f"                return new {mapped_names[i]}($\"mapped:{{value.Value}}\");",
            "            });",
            "",
            "            Assert.That(called, Is.False);",
            f"            Assert.That(mapped.IsT{next_index}, Is.True);",
            f"            Assert.That(mapped.AsT{next_index}.Value, Is.EqualTo(\"other-{next_index}\"));",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator MapT{i}Async_OnT{i}_MapsSelectedBranch()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            f"                var oneOf = {current_ctor};",
            "",
            f"                var mapped = await oneOf.MapT{i}Async(value => UniTask.FromResult(new {mapped_names[i]}($\"mapped:{{value.Value}}\")));",
            "",
            f"                Assert.That(mapped.IsT{i}, Is.True);",
            f"                Assert.That(mapped.AsT{i}.Value, Is.EqualTo(\"mapped:branch-{i}\"));",
            "            });",
            "        }",
            "",
            "        [Test]",
            f"        public void TapT{i}_OnT{i}_InvokesActionAndReturnsSameValue()",
            "        {",
            "            var captured = string.Empty;",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var tapped = oneOf.TapT{i}(value => captured = value.Value);",
            "",
            f"            Assert.That(captured, Is.EqualTo(\"branch-{i}\"));",
            "            Assert.That(tapped, Is.EqualTo(oneOf));",
            "        }",
            "",
            "        [Test]",
            f"        public void TapT{i}_WithContext_OnT{i}_PassesContextAndReturnsSameValue()",
            "        {",
            "            var captured = string.Empty;",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var tapped = oneOf.TapT{i}(\"ctx\", (context, value) => captured = $\"{{context}}:{{value.Value}}\");",
            "",
            f"            Assert.That(captured, Is.EqualTo(\"ctx:branch-{i}\"));",
            "            Assert.That(tapped, Is.EqualTo(oneOf));",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator TapT{i}Async_OnT{i}_InvokesActionAndReturnsSameValue()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            "                var captured = string.Empty;",
            f"                var oneOf = {current_ctor};",
            "",
            f"                var tapped = await oneOf.TapT{i}Async(value =>",
            "                {",
            "                    captured = value.Value;",
            "                    return UniTask.CompletedTask;",
            "                });",
            "",
            f"                Assert.That(captured, Is.EqualTo(\"branch-{i}\"));",
            "                Assert.That(tapped, Is.EqualTo(oneOf));",
            "            });",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator TapT{i}Async_WithContext_OnT{i}_PassesContextAndReturnsSameValue()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            "                var captured = string.Empty;",
            f"                var oneOf = {current_ctor};",
            "",
            f"                var tapped = await oneOf.TapT{i}Async(\"ctx\", (context, value) =>",
            "                {",
            "                    captured = $\"{context}:{value.Value}\";",
            "                    return UniTask.CompletedTask;",
            "                });",
            "",
            f"                Assert.That(captured, Is.EqualTo(\"ctx:branch-{i}\"));",
            "                Assert.That(tapped, Is.EqualTo(oneOf));",
            "            });",
            "        }",
            "",
            "        [Test]",
            f"        public void BindT{i}_OnT{i}_InvokesBinder()",
            "        {",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var bound = oneOf.BindT{i}(value => new {mapped_union}(new {mapped_names[i]}($\"bound:{{value.Value}}\")));",
            "",
            f"            Assert.That(bound.IsT{i}, Is.True);",
            f"            Assert.That(bound.AsT{i}.Value, Is.EqualTo(\"bound:branch-{i}\"));",
            "        }",
            "",
            "        [Test]",
            f"        public void BindT{i}_WithContext_OnT{i}_PassesContextIntoBinder()",
            "        {",
            f"            var oneOf = {current_ctor};",
            "",
            f"            var bound = oneOf.BindT{i}(\"ctx\", (context, value) => new {mapped_union}(new {mapped_names[i]}($\"{{context}}:{{value.Value}}\")));",
            "",
            f"            Assert.That(bound.IsT{i}, Is.True);",
            f"            Assert.That(bound.AsT{i}.Value, Is.EqualTo(\"ctx:branch-{i}\"));",
            "        }",
            "",
        ])

    for i in range(arity):
        current_ctor = ctor_expr(i, branch_ctor_expr(i, f"branch-{i}"))
        lines.extend([
            "        [Test]",
            f"        public void Switch_OnT{i}_InvokesSelectedActionWithoutThrowing()",
            "        {",
            "            var captured = string.Empty;",
            f"            var oneOf = {current_ctor};",
            "",
            "            Assert.DoesNotThrow(() => oneOf.Switch(",
        ])
        for j in range(arity):
            if j == i:
                suffix = "," if j < arity - 1 else "));"
                lines.append(f"                value => captured = value.Value{suffix}")
            else:
                suffix = "," if j < arity - 1 else "));"
                lines.append(f"                _ => Assert.Fail(\"Unexpected branch T{j} invoked\"){suffix}")
        lines.extend([
            "",
            f"            Assert.That(captured, Is.EqualTo(\"branch-{i}\"));",
            "        }",
            "",
            "        [Test]",
            f"        public void Switch_WithContext_OnT{i}_InvokesSelectedActionWithoutThrowing()",
            "        {",
            "            var captured = string.Empty;",
            f"            var oneOf = {current_ctor};",
            "",
            "            Assert.DoesNotThrow(() => oneOf.Switch(\"ctx\",",
        ])
        for j in range(arity):
            if j == i:
                suffix = "," if j < arity - 1 else "));"
                lines.append(f"                (context, value) => captured = $\"{{context}}:{{value.Value}}\"{suffix}")
            else:
                suffix = "," if j < arity - 1 else "));"
                lines.append(f"                (_, _) => Assert.Fail(\"Unexpected branch T{j} invoked\"){suffix}")
        lines.extend([
            "",
            f"            Assert.That(captured, Is.EqualTo(\"ctx:branch-{i}\"));",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator SwitchAsync_OnT{i}_InvokesSelectedActionWithoutThrowing()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            "                var captured = string.Empty;",
            f"                var oneOf = {current_ctor};",
            "",
            "                await oneOf.SwitchAsync(",
        ])
        for j in range(arity):
            if j == i:
                suffix = "," if j < arity - 1 else ");"
                lines.extend([
                    "                    value =>",
                    "                    {",
                    "                        captured = value.Value;",
                    "                        return UniTask.CompletedTask;",
                    f"                    }}{suffix}",
                ])
            else:
                suffix = "," if j < arity - 1 else ");"
                lines.extend([
                    "                    _ =>",
                    "                    {",
                    f"                        Assert.Fail(\"Unexpected branch T{j} invoked\");",
                    "                        return UniTask.CompletedTask;",
                    f"                    }}{suffix}",
                ])
        lines.extend([
            "",
            f"                Assert.That(captured, Is.EqualTo(\"branch-{i}\"));",
            "            });",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator SwitchAsync_WithContext_OnT{i}_InvokesSelectedActionWithoutThrowing()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            "                var captured = string.Empty;",
            f"                var oneOf = {current_ctor};",
            "",
            "                await oneOf.SwitchAsync(\"ctx\",",
        ])
        for j in range(arity):
            if j == i:
                suffix = "," if j < arity - 1 else ");"
                lines.extend([
                    "                    (context, value) =>",
                    "                    {",
                    "                        captured = $\"{context}:{value.Value}\";",
                    "                        return UniTask.CompletedTask;",
                    f"                    }}{suffix}",
                ])
            else:
                suffix = "," if j < arity - 1 else ");"
                lines.extend([
                    "                    (_, _) =>",
                    "                    {",
                    f"                        Assert.Fail(\"Unexpected branch T{j} invoked\");",
                    "                        return UniTask.CompletedTask;",
                    f"                    }}{suffix}",
                ])
        lines.extend([
            "",
            f"                Assert.That(captured, Is.EqualTo(\"ctx:branch-{i}\"));",
            "            });",
            "        }",
            "",
            "        [Test]",
            f"        public void Map_OnT{i}_InvokesSelectedMapper()",
            "        {",
            f"            var oneOf = {current_ctor};",
            "",
            "            var mapped = oneOf.Map(",
        ])
        for j in range(arity):
            suffix = "," if j < arity - 1 else ");"
            if j == i:
                lines.append(f"                value => $\"mapped:{{value.Value}}\"{suffix}")
            else:
                lines.append(f"                _ => throw new InvalidOperationException(\"Unexpected branch\"){suffix}")
        lines.extend([
            "",
            f"            Assert.That(mapped, Is.EqualTo(\"mapped:branch-{i}\"));",
            "        }",
            "",
            "        [UnityTest]",
            f"        public IEnumerator MapAsync_OnT{i}_InvokesSelectedMapper()",
            "        {",
            "            return UniTask.ToCoroutine(async () =>",
            "            {",
            f"                var oneOf = {current_ctor};",
            "",
            "                var mapped = await oneOf.MapAsync(",
        ])
        for j in range(arity):
            suffix = "," if j < arity - 1 else ");"
            if j == i:
                lines.append(f"                    value => UniTask.FromResult($\"mapped:{{value.Value}}\")" + suffix)
            else:
                lines.extend([
                    "                    _ =>",
                    "                    {",
                    "                        throw new InvalidOperationException(\"Unexpected branch\");",
                    f"                    }}{suffix}",
                ])
        lines.extend([
            "",
            f"                Assert.That(mapped, Is.EqualTo(\"mapped:branch-{i}\"));",
            "            });",
            "        }",
            "",
        ])

    lines.extend([
        "        [Test]",
        "        public void ToString_OnFirstBranch_FormatsBranchAndValue()",
        "        {",
        f"            var oneOf = {ctor_expr(0, branch_ctor_expr(0, 'branch-0'))};",
        "",
        "            Assert.That(oneOf.ToString(), Is.EqualTo(\"T0(branch-0)\"));",
        "        }",
        "",
        "        [Test]",
        "        public void Equality_MatchesBranchAndValue()",
        "        {",
        "            var shared = new Branch0(\"shared\");",
        f"            var left = new {union_type}(shared);",
        f"            var same = new {union_type}(shared);",
        f"            var otherValue = new {union_type}(new Branch0(\"other\"));",
        f"            var otherBranch = new {union_type}(new Branch1(\"shared\"));",
        "",
        "            Assert.That(left.Equals(same), Is.True);",
        "            Assert.That(left.Equals((object)same), Is.True);",
        "            Assert.That(left == same, Is.True);",
        "            Assert.That(left != same, Is.False);",
        "            Assert.That(left.Equals(otherValue), Is.False);",
        "            Assert.That(left.Equals(otherBranch), Is.False);",
        "        }",
        "",
        "        [Test]",
        "        public void GetHashCode_ForEqualValues_IsSame()",
        "        {",
        "            var shared = new Branch0(\"shared\");",
        f"            var left = new {union_type}(shared);",
        f"            var right = new {union_type}(shared);",
        "",
        "            Assert.That(left.GetHashCode(), Is.EqualTo(right.GetHashCode()));",
        "        }",
        "    }",
        "}",
    ])

    return "\n".join(lines) + "\n"


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate OneOf runtime and test files for arities greater than two."
    )
    parser.add_argument(
        "--max-arity",
        type=int,
        required=True,
        help="Highest arity to generate, inclusive. Must be at least 3.",
    )
    parser.add_argument(
        "--min-arity",
        type=int,
        default=3,
        help="Lowest arity to generate, inclusive. Defaults to 3.",
    )
    parser.add_argument(
        "--runtime-dir",
        type=Path,
        default=Path("Assets/Scripts/Unicore/Monads"),
        help="Directory for generated runtime files.",
    )
    parser.add_argument(
        "--tests-dir",
        type=Path,
        default=Path("Assets/Scripts/Unicore.Tests"),
        help="Directory for generated test files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.min_arity < 3:
        raise SystemExit("--min-arity must be greater than or equal to 3.")
    if args.max_arity < args.min_arity:
        raise SystemExit("--max-arity must be greater than or equal to --min-arity.")

    for arity in range(args.min_arity, args.max_arity + 1):
        runtime_path = args.runtime_dir / f"OneOf{arity}.cs"
        tests_path = args.tests_dir / f"OneOf{arity}Tests.cs"

        write_file(runtime_path, build_runtime_code(arity))
        write_file(tests_path, build_test_code(arity))

        print(f"Generated {runtime_path}")
        print(f"Generated {tests_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
