// <auto-generated>
// This file was generated automatically by Tools/CodeGen/GenerateOneOf.py.
// </auto-generated>
using System;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

namespace Unicore.Monads
{
    /// <summary>
    /// Represents discriminated union that contains one value of types <typeparamref name="T0" /> through <typeparamref name="T2" />.
    /// </summary>
    /// <typeparam name="T0">Type of branch 0.</typeparam>
    /// <typeparam name="T1">Type of branch 1.</typeparam>
    /// <typeparam name="T2">Type of branch 2.</typeparam>
    public readonly struct OneOf<T0, T1, T2> : IEquatable<OneOf<T0, T1, T2>>
    {
        private readonly object _value;
        private readonly byte _index;
        private readonly bool _hasValue;

        /// <summary>
        /// Gets branch T0 value.
        /// </summary>
        /// <value>A value stored in branch T0.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T0.</exception>
        public T0 AsT0 => _hasValue
            ? _index == 0
                ? (T0)_value
                : throw CreateWrongBranchException("T0")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T0.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T0; otherwise, <see langword="false" />.</value>
        public bool IsT0 => _index == 0;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2}" /> struct with branch T0 value.
        /// </summary>
        /// <param name="value">A value to store in branch T0.</param>
        public OneOf(T0 value)
        {
            _value = value;
            _index = 0;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T1 value.
        /// </summary>
        /// <value>A value stored in branch T1.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T1.</exception>
        public T1 AsT1 => _hasValue
            ? _index == 1
                ? (T1)_value
                : throw CreateWrongBranchException("T1")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T1.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T1; otherwise, <see langword="false" />.</value>
        public bool IsT1 => _index == 1;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2}" /> struct with branch T1 value.
        /// </summary>
        /// <param name="value">A value to store in branch T1.</param>
        public OneOf(T1 value)
        {
            _value = value;
            _index = 1;
            _hasValue = true;
        }

        /// <summary>
        /// Gets branch T2 value.
        /// </summary>
        /// <value>A value stored in branch T2.</value>
        /// <exception cref="InvalidOperationException">Current value is not stored in branch T2.</exception>
        public T2 AsT2 => _hasValue
            ? _index == 2
                ? (T2)_value
                : throw CreateWrongBranchException("T2")
            : throw CreateInvalidStateException();

        /// <summary>
        /// Gets a value that indicates whether current value is stored in branch T2.
        /// </summary>
        /// <value><see langword="true" /> if current value is stored in branch T2; otherwise, <see langword="false" />.</value>
        public bool IsT2 => _index == 2;

        /// <summary>
        /// Initializes a new instance of the <see cref="OneOf{T0, T1, T2}" /> struct with branch T2 value.
        /// </summary>
        /// <param name="value">A value to store in branch T2.</param>
        public OneOf(T2 value)
        {
            _value = value;
            _index = 2;
            _hasValue = true;
        }

        /// <summary>
        /// Projects current union into another value by selecting mapper for active branch.
        /// </summary>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <returns>A mapped value produced by selected mapper.</returns>
        public TReturn Map<TReturn>(
            Func<T0, TReturn> map0,
            Func<T1, TReturn> map1,
            Func<T2, TReturn> map2
        )
        {
            return _index switch
            {
                0 => map0(AsT0),
                1 => map1(AsT1),
                2 => map2(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value by selecting mapper for active branch and passing shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="context">A context value passed to selected mapper.</param>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <returns>A mapped value produced by selected mapper.</returns>
        public TReturn Map<TContext, TReturn>(
            TContext context,
            Func<TContext, T0, TReturn> map0,
            Func<TContext, T1, TReturn> map1,
            Func<TContext, T2, TReturn> map2
        )
        {
            return _index switch
            {
                0 => map0(context, AsT0),
                1 => map1(context, AsT1),
                2 => map2(context, AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value asynchronously by selecting mapper for active branch.
        /// </summary>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <returns>A task that produces mapped value from selected mapper.</returns>
        public UniTask<TReturn> MapAsync<TReturn>(
            Func<T0, UniTask<TReturn>> map0,
            Func<T1, UniTask<TReturn>> map1,
            Func<T2, UniTask<TReturn>> map2
        )
        {
            return _index switch
            {
                0 => map0(AsT0),
                1 => map1(AsT1),
                2 => map2(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects current union into another value asynchronously by selecting mapper for active branch and passing shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TReturn">Type of mapped value.</typeparam>
        /// <param name="context">A context value passed to selected mapper.</param>
        /// <param name="map0">A mapping function for branch T0 value.</param>
        /// <param name="map1">A mapping function for branch T1 value.</param>
        /// <param name="map2">A mapping function for branch T2 value.</param>
        /// <returns>A task that produces mapped value from selected mapper.</returns>
        public UniTask<TReturn> MapAsync<TContext, TReturn>(
            TContext context,
            Func<TContext, T0, UniTask<TReturn>> map0,
            Func<TContext, T1, UniTask<TReturn>> map1,
            Func<TContext, T2, UniTask<TReturn>> map2
        )
        {
            return _index switch
            {
                0 => map0(context, AsT0),
                1 => map1(context, AsT1),
                2 => map2(context, AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Gets branch T0 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T0 value if it exists; otherwise, the default value of <typeparamref name="T0" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T0; otherwise, <see langword="false" />.</returns>
        public bool TryGetT0(out T0 value)
        {
            if (IsT0)
            {
                value = AsT0;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T0 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T0 value or <paramref name="defaultValue" />.</returns>
        public T0 GetT0OrDefault(T0 defaultValue = default) => IsT0 ? AsT0 : defaultValue;

        /// <summary>
        /// Gets branch T1 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T1 value if it exists; otherwise, the default value of <typeparamref name="T1" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T1; otherwise, <see langword="false" />.</returns>
        public bool TryGetT1(out T1 value)
        {
            if (IsT1)
            {
                value = AsT1;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T1 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T1 value or <paramref name="defaultValue" />.</returns>
        public T1 GetT1OrDefault(T1 defaultValue = default) => IsT1 ? AsT1 : defaultValue;

        /// <summary>
        /// Gets branch T2 value when current union stores it.
        /// </summary>
        /// <param name="value">When this method returns, contains branch T2 value if it exists; otherwise, the default value of <typeparamref name="T2" />. This parameter is treated as uninitialized.</param>
        /// <returns><see langword="true" /> if current value is stored in branch T2; otherwise, <see langword="false" />.</returns>
        public bool TryGetT2(out T2 value)
        {
            if (IsT2)
            {
                value = AsT2;
                return true;
            }

            value = default;
            return false;
        }

        /// <summary>
        /// Gets branch T2 value or provided fallback when current union stores another branch.
        /// </summary>
        /// <param name="defaultValue">A fallback value.</param>
        /// <returns>A branch T2 value or <paramref name="defaultValue" />.</returns>
        public T2 GetT2OrDefault(T2 defaultValue = default) => IsT2 ? AsT2 : defaultValue;

        /// <summary>
        /// Projects branch T0 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut0">Type of mapped branch T0.</typeparam>
        /// <param name="map">A mapping function for branch T0 value.</param>
        /// <returns>A union with mapped branch T0 or original value from another branch.</returns>
        public OneOf<TOut0, T1, T2> MapT0<TOut0>(Func<T0, TOut0> map)
        {
            return IsT0 ? new OneOf<TOut0, T1, T2>(map(AsT0)) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2>(AsT1),
                2 => new OneOf<TOut0, T1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T0 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut0">Type of mapped branch T0.</typeparam>
        /// <param name="map">A mapping function for branch T0 value.</param>
        /// <returns>A task that produces union with mapped branch T0 or original value from another branch.</returns>
        public async UniTask<OneOf<TOut0, T1, T2>> MapT0Async<TOut0>(Func<T0, UniTask<TOut0>> map)
        {
            return IsT0 ? new OneOf<TOut0, T1, T2>(await map(AsT0)) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2>(AsT1),
                2 => new OneOf<TOut0, T1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T1 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut1">Type of mapped branch T1.</typeparam>
        /// <param name="map">A mapping function for branch T1 value.</param>
        /// <returns>A union with mapped branch T1 or original value from another branch.</returns>
        public OneOf<T0, TOut1, T2> MapT1<TOut1>(Func<T1, TOut1> map)
        {
            return IsT1 ? new OneOf<T0, TOut1, T2>(map(AsT1)) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2>(AsT0),
                2 => new OneOf<T0, TOut1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T1 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut1">Type of mapped branch T1.</typeparam>
        /// <param name="map">A mapping function for branch T1 value.</param>
        /// <returns>A task that produces union with mapped branch T1 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, TOut1, T2>> MapT1Async<TOut1>(Func<T1, UniTask<TOut1>> map)
        {
            return IsT1 ? new OneOf<T0, TOut1, T2>(await map(AsT1)) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2>(AsT0),
                2 => new OneOf<T0, TOut1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T2 into another branch type and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut2">Type of mapped branch T2.</typeparam>
        /// <param name="map">A mapping function for branch T2 value.</param>
        /// <returns>A union with mapped branch T2 or original value from another branch.</returns>
        public OneOf<T0, T1, TOut2> MapT2<TOut2>(Func<T2, TOut2> map)
        {
            return IsT2 ? new OneOf<T0, T1, TOut2>(map(AsT2)) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2>(AsT0),
                1 => new OneOf<T0, T1, TOut2>(AsT1),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Projects branch T2 into another branch type asynchronously and preserves all other branches unchanged.
        /// </summary>
        /// <typeparam name="TOut2">Type of mapped branch T2.</typeparam>
        /// <param name="map">A mapping function for branch T2 value.</param>
        /// <returns>A task that produces union with mapped branch T2 or original value from another branch.</returns>
        public async UniTask<OneOf<T0, T1, TOut2>> MapT2Async<TOut2>(Func<T2, UniTask<TOut2>> map)
        {
            return IsT2 ? new OneOf<T0, T1, TOut2>(await map(AsT2)) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2>(AsT0),
                1 => new OneOf<T0, T1, TOut2>(AsT1),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes action for active branch.
        /// </summary>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        public void Switch(
            Action<T0> map0,
            Action<T1> map1,
            Action<T2> map2
        )
        {
            if (IsT0)
            {
                map0(AsT0);
                return;
            }

            if (IsT1)
            {
                map1(AsT1);
                return;
            }

            if (IsT2)
            {
                map2(AsT2);
                return;
            }

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes action for active branch and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to selected action.</param>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        public void Switch<TContext>(
            TContext context,
            Action<TContext, T0> map0,
            Action<TContext, T1> map1,
            Action<TContext, T2> map2
        )
        {
            if (IsT0)
            {
                map0(context, AsT0);
                return;
            }

            if (IsT1)
            {
                map1(context, AsT1);
                return;
            }

            if (IsT2)
            {
                map2(context, AsT2);
                return;
            }

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes asynchronous action for active branch.
        /// </summary>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <returns>A task that completes when selected action finishes.</returns>
        public UniTask SwitchAsync(
            Func<T0, UniTask> map0,
            Func<T1, UniTask> map1,
            Func<T2, UniTask> map2
        )
        {
            if (IsT0)
                return map0(AsT0);

            if (IsT1)
                return map1(AsT1);

            if (IsT2)
                return map2(AsT2);

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes asynchronous action for active branch and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to selected action.</param>
        /// <param name="map0">An action for branch T0 value.</param>
        /// <param name="map1">An action for branch T1 value.</param>
        /// <param name="map2">An action for branch T2 value.</param>
        /// <returns>A task that completes when selected action finishes.</returns>
        public UniTask SwitchAsync<TContext>(
            TContext context,
            Func<TContext, T0, UniTask> map0,
            Func<TContext, T1, UniTask> map1,
            Func<TContext, T2, UniTask> map2
        )
        {
            if (IsT0)
                return map0(context, AsT0);

            if (IsT1)
                return map1(context, AsT1);

            if (IsT2)
                return map2(context, AsT2);

            throw CreateInvalidStateException();
        }

        /// <summary>
        /// Executes side effect for branch T0 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT0(Action<T0> tap)
        {
            if (IsT0)
                tap(AsT0);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T0 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT0<TContext>(TContext context, Action<TContext, T0> tap)
        {
            if (IsT0)
                tap(context, AsT0);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T0 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT0Async(Func<T0, UniTask> tap)
        {
            if (IsT0)
                await tap(AsT0);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T0 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T0 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT0Async<TContext>(TContext context, Func<TContext, T0, UniTask> tap)
        {
            if (IsT0)
                await tap(context, AsT0);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T0.
        /// </summary>
        /// <typeparam name="TOut0">Type of chained branch T0.</typeparam>
        /// <param name="binder">A function that produces next union from branch T0 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<TOut0, T1, T2> BindT0<TOut0>(Func<T0, OneOf<TOut0, T1, T2>> binder)
        {
            return IsT0 ? binder(AsT0) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2>(AsT1),
                2 => new OneOf<TOut0, T1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T0 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut0">Type of chained branch T0.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T0 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<TOut0, T1, T2> BindT0<TContext, TOut0>(TContext context, Func<TContext, T0, OneOf<TOut0, T1, T2>> binder)
        {
            return IsT0 ? binder(context, AsT0) : _index switch
            {
                1 => new OneOf<TOut0, T1, T2>(AsT1),
                2 => new OneOf<TOut0, T1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T1 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT1(Action<T1> tap)
        {
            if (IsT1)
                tap(AsT1);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T1 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT1<TContext>(TContext context, Action<TContext, T1> tap)
        {
            if (IsT1)
                tap(context, AsT1);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T1 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT1Async(Func<T1, UniTask> tap)
        {
            if (IsT1)
                await tap(AsT1);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T1 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T1 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT1Async<TContext>(TContext context, Func<TContext, T1, UniTask> tap)
        {
            if (IsT1)
                await tap(context, AsT1);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T1.
        /// </summary>
        /// <typeparam name="TOut1">Type of chained branch T1.</typeparam>
        /// <param name="binder">A function that produces next union from branch T1 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, TOut1, T2> BindT1<TOut1>(Func<T1, OneOf<T0, TOut1, T2>> binder)
        {
            return IsT1 ? binder(AsT1) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2>(AsT0),
                2 => new OneOf<T0, TOut1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T1 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut1">Type of chained branch T1.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T1 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, TOut1, T2> BindT1<TContext, TOut1>(TContext context, Func<TContext, T1, OneOf<T0, TOut1, T2>> binder)
        {
            return IsT1 ? binder(context, AsT1) : _index switch
            {
                0 => new OneOf<T0, TOut1, T2>(AsT0),
                2 => new OneOf<T0, TOut1, T2>(AsT2),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Executes side effect for branch T2 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT2(Action<T2> tap)
        {
            if (IsT2)
                tap(AsT2);

            return this;
        }

        /// <summary>
        /// Executes side effect for branch T2 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>Current union value.</returns>
        public OneOf<T0, T1, T2> TapT2<TContext>(TContext context, Action<TContext, T2> tap)
        {
            if (IsT2)
                tap(context, AsT2);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T2 and returns current union.
        /// </summary>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT2Async(Func<T2, UniTask> tap)
        {
            if (IsT2)
                await tap(AsT2);

            return this;
        }

        /// <summary>
        /// Executes asynchronous side effect for branch T2 with shared context and returns current union.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <param name="context">A context value passed to <paramref name="tap" />.</param>
        /// <param name="tap">An action for branch T2 value.</param>
        /// <returns>A task that produces current union value.</returns>
        public async UniTask<OneOf<T0, T1, T2>> TapT2Async<TContext>(TContext context, Func<TContext, T2, UniTask> tap)
        {
            if (IsT2)
                await tap(context, AsT2);

            return this;
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T2.
        /// </summary>
        /// <typeparam name="TOut2">Type of chained branch T2.</typeparam>
        /// <param name="binder">A function that produces next union from branch T2 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, TOut2> BindT2<TOut2>(Func<T2, OneOf<T0, T1, TOut2>> binder)
        {
            return IsT2 ? binder(AsT2) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2>(AsT0),
                1 => new OneOf<T0, T1, TOut2>(AsT1),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Chains another union-producing operation that runs only for branch T2 and passes shared context.
        /// </summary>
        /// <typeparam name="TContext">Type of shared context.</typeparam>
        /// <typeparam name="TOut2">Type of chained branch T2.</typeparam>
        /// <param name="context">A context value passed to <paramref name="binder" />.</param>
        /// <param name="binder">A function that produces next union from branch T2 value.</param>
        /// <returns>A chained union.</returns>
        public OneOf<T0, T1, TOut2> BindT2<TContext, TOut2>(TContext context, Func<TContext, T2, OneOf<T0, T1, TOut2>> binder)
        {
            return IsT2 ? binder(context, AsT2) : _index switch
            {
                0 => new OneOf<T0, T1, TOut2>(AsT0),
                1 => new OneOf<T0, T1, TOut2>(AsT1),
                _ => throw CreateInvalidStateException()
            };
        }

        /// <summary>
        /// Determines whether current union equals specified union.
        /// </summary>
        /// <param name="other">A union to compare with current union.</param>
        /// <returns><see langword="true" /> if current union equals <paramref name="other" />; otherwise, <see langword="false" />.</returns>
        public bool Equals(OneOf<T0, T1, T2> other)
        {
            if (_hasValue != other._hasValue || _index != other._index)
                return false;

            return _index switch
            {
                0 => EqualityComparer<T0>.Default.Equals(AsT0, other.AsT0),
                1 => EqualityComparer<T1>.Default.Equals(AsT1, other.AsT1),
                2 => EqualityComparer<T2>.Default.Equals(AsT2, other.AsT2),
                _ => false
            };
        }

        /// <summary>
        /// Determines whether current union equals specified object.
        /// </summary>
        /// <param name="obj">An object to compare with current union.</param>
        /// <returns><see langword="true" /> if <paramref name="obj" /> is equal to current union; otherwise, <see langword="false" />.</returns>
        public override bool Equals(object obj) => obj is OneOf<T0, T1, T2> other && Equals(other);

        /// <summary>
        /// Serves as hash function for current union.
        /// </summary>
        /// <returns>A hash code for current union.</returns>
        public override int GetHashCode()
        {
            return _index switch
            {
                0 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T0>.Default.GetHashCode(AsT0)),
                1 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T1>.Default.GetHashCode(AsT1)),
                2 when _hasValue => HashCode.Combine(_hasValue, _index, EqualityComparer<T2>.Default.GetHashCode(AsT2)),
                _ => HashCode.Combine(_hasValue, _index)
            };
        }

        /// <summary>
        /// Returns string representation of current union.
        /// </summary>
        /// <returns>A string that identifies active branch and stored value.</returns>
        public override string ToString()
        {
            return _index switch
            {
                0 => $"T0({AsT0})",
                1 => $"T1({AsT1})",
                2 => $"T2({AsT2})",
                _ => $"{nameof(OneOf<T0, T1, T2>)}(Invalid)"
            };
        }

        private static InvalidOperationException CreateWrongBranchException(string branchName)
            => new InvalidOperationException($"OneOf does not contain a value of type {branchName}.");

        private static ArgumentOutOfRangeException CreateInvalidStateException()
            => new ArgumentOutOfRangeException(nameof(OneOf<T0, T1, T2>), "OneOf is in an invalid state.");

        /// <summary>
        /// Determines whether two unions are equal.
        /// </summary>
        /// <param name="left">A union to compare.</param>
        /// <param name="right">A union to compare.</param>
        /// <returns><see langword="true" /> if <paramref name="left" /> equals <paramref name="right" />; otherwise, <see langword="false" />.</returns>
        public static bool operator ==(OneOf<T0, T1, T2> left, OneOf<T0, T1, T2> right) => left.Equals(right);

        /// <summary>
        /// Determines whether two unions are not equal.
        /// </summary>
        /// <param name="left">A union to compare.</param>
        /// <param name="right">A union to compare.</param>
        /// <returns><see langword="true" /> if <paramref name="left" /> does not equal <paramref name="right" />; otherwise, <see langword="false" />.</returns>
        public static bool operator !=(OneOf<T0, T1, T2> left, OneOf<T0, T1, T2> right) => !left.Equals(right);
    }
}
