// <auto-generated>
// This file was generated automatically by Tools/CodeGen/GenerateOneOf.py.
// </auto-generated>
using System;
using System.Collections;
using Cysharp.Threading.Tasks;
using NUnit.Framework;
using UnityEngine.TestTools;
using Unicore.Monads;

namespace Unicore.Tests
{
    [TestFixture]
    public sealed class OneOf3Tests
    {
        private sealed class Branch0
        {
            public Branch0(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        private sealed class Mapped0
        {
            public Mapped0(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        private sealed class Branch1
        {
            public Branch1(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        private sealed class Mapped1
        {
            public Mapped1(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        private sealed class Branch2
        {
            public Branch2(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        private sealed class Mapped2
        {
            public Mapped2(string value) => Value = value;

            public string Value { get; }

            public override string ToString() => Value;
        }

        [SetUp]
        public void SetUp()
        {
            LogAssert.ignoreFailingMessages = false;
        }

        [TearDown]
        public void TearDown()
        {
            LogAssert.NoUnexpectedReceived();
            LogAssert.ignoreFailingMessages = false;
        }

        [Test]
        public void TryGetT0_OnT0_ReturnsTrueAndValue()
        {
            var branch0 = new Branch0("branch-0");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch0);

            var result = oneOf.TryGetT0(out var value);

            Assert.That(result, Is.True);
            Assert.That(value, Is.SameAs(branch0));
        }

        [Test]
        public void TryGetT0_OnT1_ReturnsFalseAndDefault()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("other-1"));

            var result = oneOf.TryGetT0(out var value);

            Assert.That(result, Is.False);
            Assert.That(value, Is.Null);
        }

        [Test]
        public void AsT0_OnT1_ThrowsInvalidOperationExceptionWithMessage()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("other-1"));

            var exception = Assert.Throws<InvalidOperationException>(() => _ = oneOf.AsT0);

            Assert.That(exception!.Message, Is.EqualTo("OneOf does not contain a value of type T0."));
        }

        [Test]
        public void GetT0OrDefault_OnT0_ReturnsValue()
        {
            var branch0 = new Branch0("branch-0");
            var fallback = new Branch0("fallback-0");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch0);

            var value = oneOf.GetT0OrDefault(fallback);

            Assert.That(value, Is.SameAs(branch0));
        }

        [Test]
        public void GetT0OrDefault_OnT1_ReturnsFallback()
        {
            var fallback = new Branch0("fallback-0");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("other-1"));

            var value = oneOf.GetT0OrDefault(fallback);

            Assert.That(value, Is.SameAs(fallback));
        }

        [Test]
        public void TryGetT1_OnT1_ReturnsTrueAndValue()
        {
            var branch1 = new Branch1("branch-1");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch1);

            var result = oneOf.TryGetT1(out var value);

            Assert.That(result, Is.True);
            Assert.That(value, Is.SameAs(branch1));
        }

        [Test]
        public void TryGetT1_OnT2_ReturnsFalseAndDefault()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("other-2"));

            var result = oneOf.TryGetT1(out var value);

            Assert.That(result, Is.False);
            Assert.That(value, Is.Null);
        }

        [Test]
        public void AsT1_OnT2_ThrowsInvalidOperationExceptionWithMessage()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("other-2"));

            var exception = Assert.Throws<InvalidOperationException>(() => _ = oneOf.AsT1);

            Assert.That(exception!.Message, Is.EqualTo("OneOf does not contain a value of type T1."));
        }

        [Test]
        public void GetT1OrDefault_OnT1_ReturnsValue()
        {
            var branch1 = new Branch1("branch-1");
            var fallback = new Branch1("fallback-1");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch1);

            var value = oneOf.GetT1OrDefault(fallback);

            Assert.That(value, Is.SameAs(branch1));
        }

        [Test]
        public void GetT1OrDefault_OnT2_ReturnsFallback()
        {
            var fallback = new Branch1("fallback-1");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("other-2"));

            var value = oneOf.GetT1OrDefault(fallback);

            Assert.That(value, Is.SameAs(fallback));
        }

        [Test]
        public void TryGetT2_OnT2_ReturnsTrueAndValue()
        {
            var branch2 = new Branch2("branch-2");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch2);

            var result = oneOf.TryGetT2(out var value);

            Assert.That(result, Is.True);
            Assert.That(value, Is.SameAs(branch2));
        }

        [Test]
        public void TryGetT2_OnT0_ReturnsFalseAndDefault()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("other-0"));

            var result = oneOf.TryGetT2(out var value);

            Assert.That(result, Is.False);
            Assert.That(value, Is.Null);
        }

        [Test]
        public void AsT2_OnT0_ThrowsInvalidOperationExceptionWithMessage()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("other-0"));

            var exception = Assert.Throws<InvalidOperationException>(() => _ = oneOf.AsT2);

            Assert.That(exception!.Message, Is.EqualTo("OneOf does not contain a value of type T2."));
        }

        [Test]
        public void GetT2OrDefault_OnT2_ReturnsValue()
        {
            var branch2 = new Branch2("branch-2");
            var fallback = new Branch2("fallback-2");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(branch2);

            var value = oneOf.GetT2OrDefault(fallback);

            Assert.That(value, Is.SameAs(branch2));
        }

        [Test]
        public void GetT2OrDefault_OnT0_ReturnsFallback()
        {
            var fallback = new Branch2("fallback-2");
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("other-0"));

            var value = oneOf.GetT2OrDefault(fallback);

            Assert.That(value, Is.SameAs(fallback));
        }

        [Test]
        public void Map_OnDefaultValue_ThrowsArgumentOutOfRangeExceptionWithMessage()
        {
            var oneOf = default(OneOf<Branch0, Branch1, Branch2>);

            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => oneOf.Map(
                _ => "mapped-0",
                _ => "mapped-1",
                _ => "mapped-2"));

            Assert.That(exception!.Message, Does.StartWith("OneOf is in an invalid state."));
        }

        [Test]
        public void Switch_OnDefaultValue_ThrowsArgumentOutOfRangeExceptionWithMessage()
        {
            var oneOf = default(OneOf<Branch0, Branch1, Branch2>);

            var exception = Assert.Throws<ArgumentOutOfRangeException>(() => oneOf.Switch(
                _ => { },
                _ => { },
                _ => { }));

            Assert.That(exception!.Message, Does.StartWith("OneOf is in an invalid state."));
        }

        [Test]
        public void MapT0_OnT0_MapsSelectedBranch()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var mapped = oneOf.MapT0(value => new Mapped0($"mapped:{value.Value}"));

            Assert.That(mapped.IsT0, Is.True);
            Assert.That(mapped.AsT0.Value, Is.EqualTo("mapped:branch-0"));
        }

        [Test]
        public void MapT0_OnT1_PreservesOtherBranch()
        {
            var called = false;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("other-1"));

            var mapped = oneOf.MapT0(value =>
            {
                called = true;
                return new Mapped0($"mapped:{value.Value}");
            });

            Assert.That(called, Is.False);
            Assert.That(mapped.IsT1, Is.True);
            Assert.That(mapped.AsT1.Value, Is.EqualTo("other-1"));
        }

        [UnityTest]
        public IEnumerator MapT0Async_OnT0_MapsSelectedBranch()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                var mapped = await oneOf.MapT0Async(value => UniTask.FromResult(new Mapped0($"mapped:{value.Value}")));

                Assert.That(mapped.IsT0, Is.True);
                Assert.That(mapped.AsT0.Value, Is.EqualTo("mapped:branch-0"));
            });
        }

        [Test]
        public void TapT0_OnT0_InvokesActionAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var tapped = oneOf.TapT0(value => captured = value.Value);

            Assert.That(captured, Is.EqualTo("branch-0"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [Test]
        public void TapT0_WithContext_OnT0_PassesContextAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var tapped = oneOf.TapT0("ctx", (context, value) => captured = $"{context}:{value.Value}");

            Assert.That(captured, Is.EqualTo("ctx:branch-0"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [UnityTest]
        public IEnumerator TapT0Async_OnT0_InvokesActionAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                var tapped = await oneOf.TapT0Async(value =>
                {
                    captured = value.Value;
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("branch-0"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [UnityTest]
        public IEnumerator TapT0Async_WithContext_OnT0_PassesContextAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                var tapped = await oneOf.TapT0Async("ctx", (context, value) =>
                {
                    captured = $"{context}:{value.Value}";
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("ctx:branch-0"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [Test]
        public void BindT0_OnT0_InvokesBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var bound = oneOf.BindT0(value => new OneOf<Mapped0, Branch1, Branch2>(new Mapped0($"bound:{value.Value}")));

            Assert.That(bound.IsT0, Is.True);
            Assert.That(bound.AsT0.Value, Is.EqualTo("bound:branch-0"));
        }

        [Test]
        public void BindT0_WithContext_OnT0_PassesContextIntoBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var bound = oneOf.BindT0("ctx", (context, value) => new OneOf<Mapped0, Branch1, Branch2>(new Mapped0($"{context}:{value.Value}")));

            Assert.That(bound.IsT0, Is.True);
            Assert.That(bound.AsT0.Value, Is.EqualTo("ctx:branch-0"));
        }

        [Test]
        public void MapT1_OnT1_MapsSelectedBranch()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var mapped = oneOf.MapT1(value => new Mapped1($"mapped:{value.Value}"));

            Assert.That(mapped.IsT1, Is.True);
            Assert.That(mapped.AsT1.Value, Is.EqualTo("mapped:branch-1"));
        }

        [Test]
        public void MapT1_OnT2_PreservesOtherBranch()
        {
            var called = false;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("other-2"));

            var mapped = oneOf.MapT1(value =>
            {
                called = true;
                return new Mapped1($"mapped:{value.Value}");
            });

            Assert.That(called, Is.False);
            Assert.That(mapped.IsT2, Is.True);
            Assert.That(mapped.AsT2.Value, Is.EqualTo("other-2"));
        }

        [UnityTest]
        public IEnumerator MapT1Async_OnT1_MapsSelectedBranch()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                var mapped = await oneOf.MapT1Async(value => UniTask.FromResult(new Mapped1($"mapped:{value.Value}")));

                Assert.That(mapped.IsT1, Is.True);
                Assert.That(mapped.AsT1.Value, Is.EqualTo("mapped:branch-1"));
            });
        }

        [Test]
        public void TapT1_OnT1_InvokesActionAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var tapped = oneOf.TapT1(value => captured = value.Value);

            Assert.That(captured, Is.EqualTo("branch-1"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [Test]
        public void TapT1_WithContext_OnT1_PassesContextAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var tapped = oneOf.TapT1("ctx", (context, value) => captured = $"{context}:{value.Value}");

            Assert.That(captured, Is.EqualTo("ctx:branch-1"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [UnityTest]
        public IEnumerator TapT1Async_OnT1_InvokesActionAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                var tapped = await oneOf.TapT1Async(value =>
                {
                    captured = value.Value;
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("branch-1"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [UnityTest]
        public IEnumerator TapT1Async_WithContext_OnT1_PassesContextAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                var tapped = await oneOf.TapT1Async("ctx", (context, value) =>
                {
                    captured = $"{context}:{value.Value}";
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("ctx:branch-1"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [Test]
        public void BindT1_OnT1_InvokesBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var bound = oneOf.BindT1(value => new OneOf<Branch0, Mapped1, Branch2>(new Mapped1($"bound:{value.Value}")));

            Assert.That(bound.IsT1, Is.True);
            Assert.That(bound.AsT1.Value, Is.EqualTo("bound:branch-1"));
        }

        [Test]
        public void BindT1_WithContext_OnT1_PassesContextIntoBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var bound = oneOf.BindT1("ctx", (context, value) => new OneOf<Branch0, Mapped1, Branch2>(new Mapped1($"{context}:{value.Value}")));

            Assert.That(bound.IsT1, Is.True);
            Assert.That(bound.AsT1.Value, Is.EqualTo("ctx:branch-1"));
        }

        [Test]
        public void MapT2_OnT2_MapsSelectedBranch()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var mapped = oneOf.MapT2(value => new Mapped2($"mapped:{value.Value}"));

            Assert.That(mapped.IsT2, Is.True);
            Assert.That(mapped.AsT2.Value, Is.EqualTo("mapped:branch-2"));
        }

        [Test]
        public void MapT2_OnT0_PreservesOtherBranch()
        {
            var called = false;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("other-0"));

            var mapped = oneOf.MapT2(value =>
            {
                called = true;
                return new Mapped2($"mapped:{value.Value}");
            });

            Assert.That(called, Is.False);
            Assert.That(mapped.IsT0, Is.True);
            Assert.That(mapped.AsT0.Value, Is.EqualTo("other-0"));
        }

        [UnityTest]
        public IEnumerator MapT2Async_OnT2_MapsSelectedBranch()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                var mapped = await oneOf.MapT2Async(value => UniTask.FromResult(new Mapped2($"mapped:{value.Value}")));

                Assert.That(mapped.IsT2, Is.True);
                Assert.That(mapped.AsT2.Value, Is.EqualTo("mapped:branch-2"));
            });
        }

        [Test]
        public void TapT2_OnT2_InvokesActionAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var tapped = oneOf.TapT2(value => captured = value.Value);

            Assert.That(captured, Is.EqualTo("branch-2"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [Test]
        public void TapT2_WithContext_OnT2_PassesContextAndReturnsSameValue()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var tapped = oneOf.TapT2("ctx", (context, value) => captured = $"{context}:{value.Value}");

            Assert.That(captured, Is.EqualTo("ctx:branch-2"));
            Assert.That(tapped, Is.EqualTo(oneOf));
        }

        [UnityTest]
        public IEnumerator TapT2Async_OnT2_InvokesActionAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                var tapped = await oneOf.TapT2Async(value =>
                {
                    captured = value.Value;
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("branch-2"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [UnityTest]
        public IEnumerator TapT2Async_WithContext_OnT2_PassesContextAndReturnsSameValue()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                var tapped = await oneOf.TapT2Async("ctx", (context, value) =>
                {
                    captured = $"{context}:{value.Value}";
                    return UniTask.CompletedTask;
                });

                Assert.That(captured, Is.EqualTo("ctx:branch-2"));
                Assert.That(tapped, Is.EqualTo(oneOf));
            });
        }

        [Test]
        public void BindT2_OnT2_InvokesBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var bound = oneOf.BindT2(value => new OneOf<Branch0, Branch1, Mapped2>(new Mapped2($"bound:{value.Value}")));

            Assert.That(bound.IsT2, Is.True);
            Assert.That(bound.AsT2.Value, Is.EqualTo("bound:branch-2"));
        }

        [Test]
        public void BindT2_WithContext_OnT2_PassesContextIntoBinder()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var bound = oneOf.BindT2("ctx", (context, value) => new OneOf<Branch0, Branch1, Mapped2>(new Mapped2($"{context}:{value.Value}")));

            Assert.That(bound.IsT2, Is.True);
            Assert.That(bound.AsT2.Value, Is.EqualTo("ctx:branch-2"));
        }

        [Test]
        public void Switch_OnT0_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            Assert.DoesNotThrow(() => oneOf.Switch(
                value => captured = value.Value,
                _ => Assert.Fail("Unexpected branch T1 invoked"),
                _ => Assert.Fail("Unexpected branch T2 invoked")));

            Assert.That(captured, Is.EqualTo("branch-0"));
        }

        [Test]
        public void Switch_WithContext_OnT0_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            Assert.DoesNotThrow(() => oneOf.Switch("ctx",
                (context, value) => captured = $"{context}:{value.Value}",
                (_, _) => Assert.Fail("Unexpected branch T1 invoked"),
                (_, _) => Assert.Fail("Unexpected branch T2 invoked")));

            Assert.That(captured, Is.EqualTo("ctx:branch-0"));
        }

        [UnityTest]
        public IEnumerator SwitchAsync_OnT0_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                await oneOf.SwitchAsync(
                    value =>
                    {
                        captured = value.Value;
                        return UniTask.CompletedTask;
                    },
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T1 invoked");
                        return UniTask.CompletedTask;
                    },
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T2 invoked");
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("branch-0"));
            });
        }

        [UnityTest]
        public IEnumerator SwitchAsync_WithContext_OnT0_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                await oneOf.SwitchAsync("ctx",
                    (context, value) =>
                    {
                        captured = $"{context}:{value.Value}";
                        return UniTask.CompletedTask;
                    },
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T1 invoked");
                        return UniTask.CompletedTask;
                    },
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T2 invoked");
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("ctx:branch-0"));
            });
        }

        [Test]
        public void Map_OnT0_InvokesSelectedMapper()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            var mapped = oneOf.Map(
                value => $"mapped:{value.Value}",
                _ => throw new InvalidOperationException("Unexpected branch"),
                _ => throw new InvalidOperationException("Unexpected branch"));

            Assert.That(mapped, Is.EqualTo("mapped:branch-0"));
        }

        [UnityTest]
        public IEnumerator MapAsync_OnT0_InvokesSelectedMapper()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

                var mapped = await oneOf.MapAsync(
                    value => UniTask.FromResult($"mapped:{value.Value}"),
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    },
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    });

                Assert.That(mapped, Is.EqualTo("mapped:branch-0"));
            });
        }

        [Test]
        public void Switch_OnT1_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            Assert.DoesNotThrow(() => oneOf.Switch(
                _ => Assert.Fail("Unexpected branch T0 invoked"),
                value => captured = value.Value,
                _ => Assert.Fail("Unexpected branch T2 invoked")));

            Assert.That(captured, Is.EqualTo("branch-1"));
        }

        [Test]
        public void Switch_WithContext_OnT1_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            Assert.DoesNotThrow(() => oneOf.Switch("ctx",
                (_, _) => Assert.Fail("Unexpected branch T0 invoked"),
                (context, value) => captured = $"{context}:{value.Value}",
                (_, _) => Assert.Fail("Unexpected branch T2 invoked")));

            Assert.That(captured, Is.EqualTo("ctx:branch-1"));
        }

        [UnityTest]
        public IEnumerator SwitchAsync_OnT1_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                await oneOf.SwitchAsync(
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T0 invoked");
                        return UniTask.CompletedTask;
                    },
                    value =>
                    {
                        captured = value.Value;
                        return UniTask.CompletedTask;
                    },
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T2 invoked");
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("branch-1"));
            });
        }

        [UnityTest]
        public IEnumerator SwitchAsync_WithContext_OnT1_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                await oneOf.SwitchAsync("ctx",
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T0 invoked");
                        return UniTask.CompletedTask;
                    },
                    (context, value) =>
                    {
                        captured = $"{context}:{value.Value}";
                        return UniTask.CompletedTask;
                    },
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T2 invoked");
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("ctx:branch-1"));
            });
        }

        [Test]
        public void Map_OnT1_InvokesSelectedMapper()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

            var mapped = oneOf.Map(
                _ => throw new InvalidOperationException("Unexpected branch"),
                value => $"mapped:{value.Value}",
                _ => throw new InvalidOperationException("Unexpected branch"));

            Assert.That(mapped, Is.EqualTo("mapped:branch-1"));
        }

        [UnityTest]
        public IEnumerator MapAsync_OnT1_InvokesSelectedMapper()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch1("branch-1"));

                var mapped = await oneOf.MapAsync(
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    },
                    value => UniTask.FromResult($"mapped:{value.Value}"),
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    });

                Assert.That(mapped, Is.EqualTo("mapped:branch-1"));
            });
        }

        [Test]
        public void Switch_OnT2_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            Assert.DoesNotThrow(() => oneOf.Switch(
                _ => Assert.Fail("Unexpected branch T0 invoked"),
                _ => Assert.Fail("Unexpected branch T1 invoked"),
                value => captured = value.Value));

            Assert.That(captured, Is.EqualTo("branch-2"));
        }

        [Test]
        public void Switch_WithContext_OnT2_InvokesSelectedActionWithoutThrowing()
        {
            var captured = string.Empty;
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            Assert.DoesNotThrow(() => oneOf.Switch("ctx",
                (_, _) => Assert.Fail("Unexpected branch T0 invoked"),
                (_, _) => Assert.Fail("Unexpected branch T1 invoked"),
                (context, value) => captured = $"{context}:{value.Value}"));

            Assert.That(captured, Is.EqualTo("ctx:branch-2"));
        }

        [UnityTest]
        public IEnumerator SwitchAsync_OnT2_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                await oneOf.SwitchAsync(
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T0 invoked");
                        return UniTask.CompletedTask;
                    },
                    _ =>
                    {
                        Assert.Fail("Unexpected branch T1 invoked");
                        return UniTask.CompletedTask;
                    },
                    value =>
                    {
                        captured = value.Value;
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("branch-2"));
            });
        }

        [UnityTest]
        public IEnumerator SwitchAsync_WithContext_OnT2_InvokesSelectedActionWithoutThrowing()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var captured = string.Empty;
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                await oneOf.SwitchAsync("ctx",
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T0 invoked");
                        return UniTask.CompletedTask;
                    },
                    (_, _) =>
                    {
                        Assert.Fail("Unexpected branch T1 invoked");
                        return UniTask.CompletedTask;
                    },
                    (context, value) =>
                    {
                        captured = $"{context}:{value.Value}";
                        return UniTask.CompletedTask;
                    });

                Assert.That(captured, Is.EqualTo("ctx:branch-2"));
            });
        }

        [Test]
        public void Map_OnT2_InvokesSelectedMapper()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

            var mapped = oneOf.Map(
                _ => throw new InvalidOperationException("Unexpected branch"),
                _ => throw new InvalidOperationException("Unexpected branch"),
                value => $"mapped:{value.Value}");

            Assert.That(mapped, Is.EqualTo("mapped:branch-2"));
        }

        [UnityTest]
        public IEnumerator MapAsync_OnT2_InvokesSelectedMapper()
        {
            return UniTask.ToCoroutine(async () =>
            {
                var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch2("branch-2"));

                var mapped = await oneOf.MapAsync(
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    },
                    _ =>
                    {
                        throw new InvalidOperationException("Unexpected branch");
                    },
                    value => UniTask.FromResult($"mapped:{value.Value}"));

                Assert.That(mapped, Is.EqualTo("mapped:branch-2"));
            });
        }

        [Test]
        public void ToString_OnFirstBranch_FormatsBranchAndValue()
        {
            var oneOf = new OneOf<Branch0, Branch1, Branch2>(new Branch0("branch-0"));

            Assert.That(oneOf.ToString(), Is.EqualTo("T0(branch-0)"));
        }

        [Test]
        public void Equality_MatchesBranchAndValue()
        {
            var shared = new Branch0("shared");
            var left = new OneOf<Branch0, Branch1, Branch2>(shared);
            var same = new OneOf<Branch0, Branch1, Branch2>(shared);
            var otherValue = new OneOf<Branch0, Branch1, Branch2>(new Branch0("other"));
            var otherBranch = new OneOf<Branch0, Branch1, Branch2>(new Branch1("shared"));

            Assert.That(left.Equals(same), Is.True);
            Assert.That(left.Equals((object)same), Is.True);
            Assert.That(left == same, Is.True);
            Assert.That(left != same, Is.False);
            Assert.That(left.Equals(otherValue), Is.False);
            Assert.That(left.Equals(otherBranch), Is.False);
        }

        [Test]
        public void GetHashCode_ForEqualValues_IsSame()
        {
            var shared = new Branch0("shared");
            var left = new OneOf<Branch0, Branch1, Branch2>(shared);
            var right = new OneOf<Branch0, Branch1, Branch2>(shared);

            Assert.That(left.GetHashCode(), Is.EqualTo(right.GetHashCode()));
        }
    }
}
